// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             (unknown)
// source: api/v1/scannerapi/api.proto

package scannerapi

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	API_CreateScanner_FullMethodName      = "/com.spirl.api.v1.scanner.API/CreateScanner"
	API_UpdateScanner_FullMethodName      = "/com.spirl.api.v1.scanner.API/UpdateScanner"
	API_DeleteScanner_FullMethodName      = "/com.spirl.api.v1.scanner.API/DeleteScanner"
	API_ListScanners_FullMethodName       = "/com.spirl.api.v1.scanner.API/ListScanners"
	API_GetScanner_FullMethodName         = "/com.spirl.api.v1.scanner.API/GetScanner"
	API_ListScannerTargets_FullMethodName = "/com.spirl.api.v1.scanner.API/ListScannerTargets"
)

// APIClient is the client API for API service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type APIClient interface {
	// Endpoint to create a scanner for the organization.
	CreateScanner(ctx context.Context, in *CreateScannerRequest, opts ...grpc.CallOption) (*CreateScannerResponse, error)
	// Endpoint to update a SaaS scanner with connector configuration.
	UpdateScanner(ctx context.Context, in *UpdateScannerRequest, opts ...grpc.CallOption) (*UpdateScannerResponse, error)
	// Endpoint to delete a scanner for the organization.
	DeleteScanner(ctx context.Context, in *DeleteScannerRequest, opts ...grpc.CallOption) (*DeleteScannerResponse, error)
	// Endpoint to list scanners for the organization.
	ListScanners(ctx context.Context, in *ListScannersRequest, opts ...grpc.CallOption) (*ListScannersResponse, error)
	// Endpoint to get a scanner by name.
	GetScanner(ctx context.Context, in *GetScannerRequest, opts ...grpc.CallOption) (*GetScannerResponse, error)
	// Endpoint to list scan targets for a scanner.
	ListScannerTargets(ctx context.Context, in *ListScannerTargetsRequest, opts ...grpc.CallOption) (*ListScannerTargetsResponse, error)
}

type aPIClient struct {
	cc grpc.ClientConnInterface
}

func NewAPIClient(cc grpc.ClientConnInterface) APIClient {
	return &aPIClient{cc}
}

func (c *aPIClient) CreateScanner(ctx context.Context, in *CreateScannerRequest, opts ...grpc.CallOption) (*CreateScannerResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateScannerResponse)
	err := c.cc.Invoke(ctx, API_CreateScanner_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aPIClient) UpdateScanner(ctx context.Context, in *UpdateScannerRequest, opts ...grpc.CallOption) (*UpdateScannerResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateScannerResponse)
	err := c.cc.Invoke(ctx, API_UpdateScanner_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aPIClient) DeleteScanner(ctx context.Context, in *DeleteScannerRequest, opts ...grpc.CallOption) (*DeleteScannerResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteScannerResponse)
	err := c.cc.Invoke(ctx, API_DeleteScanner_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aPIClient) ListScanners(ctx context.Context, in *ListScannersRequest, opts ...grpc.CallOption) (*ListScannersResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListScannersResponse)
	err := c.cc.Invoke(ctx, API_ListScanners_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aPIClient) GetScanner(ctx context.Context, in *GetScannerRequest, opts ...grpc.CallOption) (*GetScannerResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetScannerResponse)
	err := c.cc.Invoke(ctx, API_GetScanner_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aPIClient) ListScannerTargets(ctx context.Context, in *ListScannerTargetsRequest, opts ...grpc.CallOption) (*ListScannerTargetsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListScannerTargetsResponse)
	err := c.cc.Invoke(ctx, API_ListScannerTargets_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// APIServer is the server API for API service.
// All implementations must embed UnimplementedAPIServer
// for forward compatibility.
type APIServer interface {
	// Endpoint to create a scanner for the organization.
	CreateScanner(context.Context, *CreateScannerRequest) (*CreateScannerResponse, error)
	// Endpoint to update a SaaS scanner with connector configuration.
	UpdateScanner(context.Context, *UpdateScannerRequest) (*UpdateScannerResponse, error)
	// Endpoint to delete a scanner for the organization.
	DeleteScanner(context.Context, *DeleteScannerRequest) (*DeleteScannerResponse, error)
	// Endpoint to list scanners for the organization.
	ListScanners(context.Context, *ListScannersRequest) (*ListScannersResponse, error)
	// Endpoint to get a scanner by name.
	GetScanner(context.Context, *GetScannerRequest) (*GetScannerResponse, error)
	// Endpoint to list scan targets for a scanner.
	ListScannerTargets(context.Context, *ListScannerTargetsRequest) (*ListScannerTargetsResponse, error)
	mustEmbedUnimplementedAPIServer()
}

// UnimplementedAPIServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAPIServer struct{}

func (UnimplementedAPIServer) CreateScanner(context.Context, *CreateScannerRequest) (*CreateScannerResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateScanner not implemented")
}
func (UnimplementedAPIServer) UpdateScanner(context.Context, *UpdateScannerRequest) (*UpdateScannerResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateScanner not implemented")
}
func (UnimplementedAPIServer) DeleteScanner(context.Context, *DeleteScannerRequest) (*DeleteScannerResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteScanner not implemented")
}
func (UnimplementedAPIServer) ListScanners(context.Context, *ListScannersRequest) (*ListScannersResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListScanners not implemented")
}
func (UnimplementedAPIServer) GetScanner(context.Context, *GetScannerRequest) (*GetScannerResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetScanner not implemented")
}
func (UnimplementedAPIServer) ListScannerTargets(context.Context, *ListScannerTargetsRequest) (*ListScannerTargetsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListScannerTargets not implemented")
}
func (UnimplementedAPIServer) mustEmbedUnimplementedAPIServer() {}
func (UnimplementedAPIServer) testEmbeddedByValue()             {}

// UnsafeAPIServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to APIServer will
// result in compilation errors.
type UnsafeAPIServer interface {
	mustEmbedUnimplementedAPIServer()
}

func RegisterAPIServer(s grpc.ServiceRegistrar, srv APIServer) {
	// If the following call pancis, it indicates UnimplementedAPIServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&API_ServiceDesc, srv)
}

func _API_CreateScanner_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateScannerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(APIServer).CreateScanner(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: API_CreateScanner_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(APIServer).CreateScanner(ctx, req.(*CreateScannerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _API_UpdateScanner_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateScannerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(APIServer).UpdateScanner(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: API_UpdateScanner_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(APIServer).UpdateScanner(ctx, req.(*UpdateScannerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _API_DeleteScanner_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteScannerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(APIServer).DeleteScanner(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: API_DeleteScanner_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(APIServer).DeleteScanner(ctx, req.(*DeleteScannerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _API_ListScanners_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListScannersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(APIServer).ListScanners(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: API_ListScanners_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(APIServer).ListScanners(ctx, req.(*ListScannersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _API_GetScanner_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetScannerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(APIServer).GetScanner(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: API_GetScanner_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(APIServer).GetScanner(ctx, req.(*GetScannerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _API_ListScannerTargets_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListScannerTargetsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(APIServer).ListScannerTargets(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: API_ListScannerTargets_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(APIServer).ListScannerTargets(ctx, req.(*ListScannerTargetsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// API_ServiceDesc is the grpc.ServiceDesc for API service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var API_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "com.spirl.api.v1.scanner.API",
	HandlerType: (*APIServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateScanner",
			Handler:    _API_CreateScanner_Handler,
		},
		{
			MethodName: "UpdateScanner",
			Handler:    _API_UpdateScanner_Handler,
		},
		{
			MethodName: "DeleteScanner",
			Handler:    _API_DeleteScanner_Handler,
		},
		{
			MethodName: "ListScanners",
			Handler:    _API_ListScanners_Handler,
		},
		{
			MethodName: "GetScanner",
			Handler:    _API_GetScanner_Handler,
		},
		{
			MethodName: "ListScannerTargets",
			Handler:    _API_ListScannerTargets_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/v1/scannerapi/api.proto",
}
