// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             (unknown)
// source: api/v1/alertapi/api.proto

package alertapi

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	API_GetAlertConfig_FullMethodName        = "/com.spirl.api.v1.alert.API/GetAlertConfig"
	API_ListAlertConfigs_FullMethodName      = "/com.spirl.api.v1.alert.API/ListAlertConfigs"
	API_CreateAlertConfig_FullMethodName     = "/com.spirl.api.v1.alert.API/CreateAlertConfig"
	API_DeleteAlertConfig_FullMethodName     = "/com.spirl.api.v1.alert.API/DeleteAlertConfig"
	API_SendVerificationEmail_FullMethodName = "/com.spirl.api.v1.alert.API/SendVerificationEmail"
	API_VerifyEmail_FullMethodName           = "/com.spirl.api.v1.alert.API/VerifyEmail"
	API_ListAlerts_FullMethodName            = "/com.spirl.api.v1.alert.API/ListAlerts"
	API_CreateTestAlert_FullMethodName       = "/com.spirl.api.v1.alert.API/CreateTestAlert"
)

// APIClient is the client API for API service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type APIClient interface {
	// Retrieves the alert configuration for a specific organization and
	// trust domain.
	GetAlertConfig(ctx context.Context, in *GetAlertConfigRequest, opts ...grpc.CallOption) (*GetAlertConfigResponse, error)
	// Lists all alert configurations of an organization across all its trust
	// domains.
	ListAlertConfigs(ctx context.Context, in *ListAlertConfigsRequest, opts ...grpc.CallOption) (*ListAlertConfigsResponse, error)
	// Creates a new alert configuration for a specific organization and
	// trust domain. If an alert configuration already exists for the given
	// organization and trust domain, an error will be returned.
	CreateAlertConfig(ctx context.Context, in *CreateAlertConfigRequest, opts ...grpc.CallOption) (*CreateAlertConfigResponse, error)
	// Deletes the alert configuration for a specific organization and
	// trust domain. If no alert configuration exists for
	// the given organization and trust domain, an error will be returned.
	DeleteAlertConfig(ctx context.Context, in *DeleteAlertConfigRequest, opts ...grpc.CallOption) (*DeleteAlertConfigResponse, error)
	// Sends a verification email to the specified email address in the
	// alert configuration. The email will contain a verification link
	// that the recipient must click to verify their email address. If the email
	// address is already verified, this operation will resend the verification
	// email.
	SendVerificationEmail(ctx context.Context, in *SendVerificationEmailRequest, opts ...grpc.CallOption) (*SendVerificationEmailResponse, error)
	// Verifies the email address associated with the given verification code.
	// This operation is typically triggered when the recipient clicks the
	// verification link in the email. If the code is valid and not expired,
	// the email address will be marked as verified. If the code is invalid or
	// expired, an error will be returned.
	VerifyEmail(ctx context.Context, in *VerifyEmailRequest, opts ...grpc.CallOption) (*VerifyEmailResponse, error)
	// Lists all alerts associated with a specific alert configuration.
	ListAlerts(ctx context.Context, in *ListAlertsRequest, opts ...grpc.CallOption) (*ListAlertsResponse, error)
	// Creates a test alert for the specified alert configuration. This is
	// typically used to verify that the alerting system is functioning correctly
	// and that alerts are being sent to the configured recipients.
	CreateTestAlert(ctx context.Context, in *CreateTestAlertRequest, opts ...grpc.CallOption) (*CreateTestAlertResponse, error)
}

type aPIClient struct {
	cc grpc.ClientConnInterface
}

func NewAPIClient(cc grpc.ClientConnInterface) APIClient {
	return &aPIClient{cc}
}

func (c *aPIClient) GetAlertConfig(ctx context.Context, in *GetAlertConfigRequest, opts ...grpc.CallOption) (*GetAlertConfigResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetAlertConfigResponse)
	err := c.cc.Invoke(ctx, API_GetAlertConfig_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aPIClient) ListAlertConfigs(ctx context.Context, in *ListAlertConfigsRequest, opts ...grpc.CallOption) (*ListAlertConfigsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListAlertConfigsResponse)
	err := c.cc.Invoke(ctx, API_ListAlertConfigs_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aPIClient) CreateAlertConfig(ctx context.Context, in *CreateAlertConfigRequest, opts ...grpc.CallOption) (*CreateAlertConfigResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateAlertConfigResponse)
	err := c.cc.Invoke(ctx, API_CreateAlertConfig_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aPIClient) DeleteAlertConfig(ctx context.Context, in *DeleteAlertConfigRequest, opts ...grpc.CallOption) (*DeleteAlertConfigResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteAlertConfigResponse)
	err := c.cc.Invoke(ctx, API_DeleteAlertConfig_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aPIClient) SendVerificationEmail(ctx context.Context, in *SendVerificationEmailRequest, opts ...grpc.CallOption) (*SendVerificationEmailResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SendVerificationEmailResponse)
	err := c.cc.Invoke(ctx, API_SendVerificationEmail_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aPIClient) VerifyEmail(ctx context.Context, in *VerifyEmailRequest, opts ...grpc.CallOption) (*VerifyEmailResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(VerifyEmailResponse)
	err := c.cc.Invoke(ctx, API_VerifyEmail_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aPIClient) ListAlerts(ctx context.Context, in *ListAlertsRequest, opts ...grpc.CallOption) (*ListAlertsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListAlertsResponse)
	err := c.cc.Invoke(ctx, API_ListAlerts_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aPIClient) CreateTestAlert(ctx context.Context, in *CreateTestAlertRequest, opts ...grpc.CallOption) (*CreateTestAlertResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateTestAlertResponse)
	err := c.cc.Invoke(ctx, API_CreateTestAlert_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// APIServer is the server API for API service.
// All implementations must embed UnimplementedAPIServer
// for forward compatibility.
type APIServer interface {
	// Retrieves the alert configuration for a specific organization and
	// trust domain.
	GetAlertConfig(context.Context, *GetAlertConfigRequest) (*GetAlertConfigResponse, error)
	// Lists all alert configurations of an organization across all its trust
	// domains.
	ListAlertConfigs(context.Context, *ListAlertConfigsRequest) (*ListAlertConfigsResponse, error)
	// Creates a new alert configuration for a specific organization and
	// trust domain. If an alert configuration already exists for the given
	// organization and trust domain, an error will be returned.
	CreateAlertConfig(context.Context, *CreateAlertConfigRequest) (*CreateAlertConfigResponse, error)
	// Deletes the alert configuration for a specific organization and
	// trust domain. If no alert configuration exists for
	// the given organization and trust domain, an error will be returned.
	DeleteAlertConfig(context.Context, *DeleteAlertConfigRequest) (*DeleteAlertConfigResponse, error)
	// Sends a verification email to the specified email address in the
	// alert configuration. The email will contain a verification link
	// that the recipient must click to verify their email address. If the email
	// address is already verified, this operation will resend the verification
	// email.
	SendVerificationEmail(context.Context, *SendVerificationEmailRequest) (*SendVerificationEmailResponse, error)
	// Verifies the email address associated with the given verification code.
	// This operation is typically triggered when the recipient clicks the
	// verification link in the email. If the code is valid and not expired,
	// the email address will be marked as verified. If the code is invalid or
	// expired, an error will be returned.
	VerifyEmail(context.Context, *VerifyEmailRequest) (*VerifyEmailResponse, error)
	// Lists all alerts associated with a specific alert configuration.
	ListAlerts(context.Context, *ListAlertsRequest) (*ListAlertsResponse, error)
	// Creates a test alert for the specified alert configuration. This is
	// typically used to verify that the alerting system is functioning correctly
	// and that alerts are being sent to the configured recipients.
	CreateTestAlert(context.Context, *CreateTestAlertRequest) (*CreateTestAlertResponse, error)
	mustEmbedUnimplementedAPIServer()
}

// UnimplementedAPIServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAPIServer struct{}

func (UnimplementedAPIServer) GetAlertConfig(context.Context, *GetAlertConfigRequest) (*GetAlertConfigResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAlertConfig not implemented")
}
func (UnimplementedAPIServer) ListAlertConfigs(context.Context, *ListAlertConfigsRequest) (*ListAlertConfigsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListAlertConfigs not implemented")
}
func (UnimplementedAPIServer) CreateAlertConfig(context.Context, *CreateAlertConfigRequest) (*CreateAlertConfigResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateAlertConfig not implemented")
}
func (UnimplementedAPIServer) DeleteAlertConfig(context.Context, *DeleteAlertConfigRequest) (*DeleteAlertConfigResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteAlertConfig not implemented")
}
func (UnimplementedAPIServer) SendVerificationEmail(context.Context, *SendVerificationEmailRequest) (*SendVerificationEmailResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendVerificationEmail not implemented")
}
func (UnimplementedAPIServer) VerifyEmail(context.Context, *VerifyEmailRequest) (*VerifyEmailResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method VerifyEmail not implemented")
}
func (UnimplementedAPIServer) ListAlerts(context.Context, *ListAlertsRequest) (*ListAlertsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListAlerts not implemented")
}
func (UnimplementedAPIServer) CreateTestAlert(context.Context, *CreateTestAlertRequest) (*CreateTestAlertResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateTestAlert not implemented")
}
func (UnimplementedAPIServer) mustEmbedUnimplementedAPIServer() {}
func (UnimplementedAPIServer) testEmbeddedByValue()             {}

// UnsafeAPIServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to APIServer will
// result in compilation errors.
type UnsafeAPIServer interface {
	mustEmbedUnimplementedAPIServer()
}

func RegisterAPIServer(s grpc.ServiceRegistrar, srv APIServer) {
	// If the following call pancis, it indicates UnimplementedAPIServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&API_ServiceDesc, srv)
}

func _API_GetAlertConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAlertConfigRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(APIServer).GetAlertConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: API_GetAlertConfig_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(APIServer).GetAlertConfig(ctx, req.(*GetAlertConfigRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _API_ListAlertConfigs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListAlertConfigsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(APIServer).ListAlertConfigs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: API_ListAlertConfigs_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(APIServer).ListAlertConfigs(ctx, req.(*ListAlertConfigsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _API_CreateAlertConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateAlertConfigRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(APIServer).CreateAlertConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: API_CreateAlertConfig_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(APIServer).CreateAlertConfig(ctx, req.(*CreateAlertConfigRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _API_DeleteAlertConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteAlertConfigRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(APIServer).DeleteAlertConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: API_DeleteAlertConfig_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(APIServer).DeleteAlertConfig(ctx, req.(*DeleteAlertConfigRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _API_SendVerificationEmail_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SendVerificationEmailRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(APIServer).SendVerificationEmail(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: API_SendVerificationEmail_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(APIServer).SendVerificationEmail(ctx, req.(*SendVerificationEmailRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _API_VerifyEmail_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VerifyEmailRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(APIServer).VerifyEmail(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: API_VerifyEmail_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(APIServer).VerifyEmail(ctx, req.(*VerifyEmailRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _API_ListAlerts_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListAlertsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(APIServer).ListAlerts(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: API_ListAlerts_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(APIServer).ListAlerts(ctx, req.(*ListAlertsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _API_CreateTestAlert_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateTestAlertRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(APIServer).CreateTestAlert(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: API_CreateTestAlert_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(APIServer).CreateTestAlert(ctx, req.(*CreateTestAlertRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// API_ServiceDesc is the grpc.ServiceDesc for API service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var API_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "com.spirl.api.v1.alert.API",
	HandlerType: (*APIServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetAlertConfig",
			Handler:    _API_GetAlertConfig_Handler,
		},
		{
			MethodName: "ListAlertConfigs",
			Handler:    _API_ListAlertConfigs_Handler,
		},
		{
			MethodName: "CreateAlertConfig",
			Handler:    _API_CreateAlertConfig_Handler,
		},
		{
			MethodName: "DeleteAlertConfig",
			Handler:    _API_DeleteAlertConfig_Handler,
		},
		{
			MethodName: "SendVerificationEmail",
			Handler:    _API_SendVerificationEmail_Handler,
		},
		{
			MethodName: "VerifyEmail",
			Handler:    _API_VerifyEmail_Handler,
		},
		{
			MethodName: "ListAlerts",
			Handler:    _API_ListAlerts_Handler,
		},
		{
			MethodName: "CreateTestAlert",
			Handler:    _API_CreateTestAlert_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/v1/alertapi/api.proto",
}
