// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        (unknown)
// source: api/v1/sessionapi/api.proto

package sessionapi

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type LoginRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Request:
	//
	//	*LoginRequest_Start
	//	*LoginRequest_Finish
	//	*LoginRequest_ChooseOrg
	Request isLoginRequest_Request `protobuf_oneof:"request"`
}

func (x *LoginRequest) Reset() {
	*x = LoginRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_v1_sessionapi_api_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LoginRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginRequest) ProtoMessage() {}

func (x *LoginRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_sessionapi_api_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginRequest.ProtoReflect.Descriptor instead.
func (*LoginRequest) Descriptor() ([]byte, []int) {
	return file_api_v1_sessionapi_api_proto_rawDescGZIP(), []int{0}
}

func (m *LoginRequest) GetRequest() isLoginRequest_Request {
	if m != nil {
		return m.Request
	}
	return nil
}

func (x *LoginRequest) GetStart() *StartLoginRequest {
	if x, ok := x.GetRequest().(*LoginRequest_Start); ok {
		return x.Start
	}
	return nil
}

func (x *LoginRequest) GetFinish() *FinishLoginRequest {
	if x, ok := x.GetRequest().(*LoginRequest_Finish); ok {
		return x.Finish
	}
	return nil
}

func (x *LoginRequest) GetChooseOrg() *ChooseOrgRequest {
	if x, ok := x.GetRequest().(*LoginRequest_ChooseOrg); ok {
		return x.ChooseOrg
	}
	return nil
}

type isLoginRequest_Request interface {
	isLoginRequest_Request()
}

type LoginRequest_Start struct {
	Start *StartLoginRequest `protobuf:"bytes,1,opt,name=start,proto3,oneof"`
}

type LoginRequest_Finish struct {
	Finish *FinishLoginRequest `protobuf:"bytes,2,opt,name=finish,proto3,oneof"`
}

type LoginRequest_ChooseOrg struct {
	ChooseOrg *ChooseOrgRequest `protobuf:"bytes,3,opt,name=choose_org,json=chooseOrg,proto3,oneof"`
}

func (*LoginRequest_Start) isLoginRequest_Request() {}

func (*LoginRequest_Finish) isLoginRequest_Request() {}

func (*LoginRequest_ChooseOrg) isLoginRequest_Request() {}

type LoginResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Response:
	//
	//	*LoginResponse_Start
	//	*LoginResponse_Finish
	//	*LoginResponse_ChooseOrg
	Response isLoginResponse_Response `protobuf_oneof:"response"`
}

func (x *LoginResponse) Reset() {
	*x = LoginResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_v1_sessionapi_api_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LoginResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginResponse) ProtoMessage() {}

func (x *LoginResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_sessionapi_api_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginResponse.ProtoReflect.Descriptor instead.
func (*LoginResponse) Descriptor() ([]byte, []int) {
	return file_api_v1_sessionapi_api_proto_rawDescGZIP(), []int{1}
}

func (m *LoginResponse) GetResponse() isLoginResponse_Response {
	if m != nil {
		return m.Response
	}
	return nil
}

func (x *LoginResponse) GetStart() *StartLoginResponse {
	if x, ok := x.GetResponse().(*LoginResponse_Start); ok {
		return x.Start
	}
	return nil
}

func (x *LoginResponse) GetFinish() *FinishLoginResponse {
	if x, ok := x.GetResponse().(*LoginResponse_Finish); ok {
		return x.Finish
	}
	return nil
}

func (x *LoginResponse) GetChooseOrg() *ChooseOrgResponse {
	if x, ok := x.GetResponse().(*LoginResponse_ChooseOrg); ok {
		return x.ChooseOrg
	}
	return nil
}

type isLoginResponse_Response interface {
	isLoginResponse_Response()
}

type LoginResponse_Start struct {
	Start *StartLoginResponse `protobuf:"bytes,1,opt,name=start,proto3,oneof"`
}

type LoginResponse_Finish struct {
	Finish *FinishLoginResponse `protobuf:"bytes,2,opt,name=finish,proto3,oneof"`
}

type LoginResponse_ChooseOrg struct {
	ChooseOrg *ChooseOrgResponse `protobuf:"bytes,3,opt,name=choose_org,json=chooseOrg,proto3,oneof"`
}

func (*LoginResponse_Start) isLoginResponse_Response() {}

func (*LoginResponse_Finish) isLoginResponse_Response() {}

func (*LoginResponse_ChooseOrg) isLoginResponse_Response() {}

type LogoutRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *LogoutRequest) Reset() {
	*x = LogoutRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_v1_sessionapi_api_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LogoutRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogoutRequest) ProtoMessage() {}

func (x *LogoutRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_sessionapi_api_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogoutRequest.ProtoReflect.Descriptor instead.
func (*LogoutRequest) Descriptor() ([]byte, []int) {
	return file_api_v1_sessionapi_api_proto_rawDescGZIP(), []int{2}
}

type LogoutResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *LogoutResponse) Reset() {
	*x = LogoutResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_v1_sessionapi_api_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LogoutResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogoutResponse) ProtoMessage() {}

func (x *LogoutResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_sessionapi_api_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogoutResponse.ProtoReflect.Descriptor instead.
func (*LogoutResponse) Descriptor() ([]byte, []int) {
	return file_api_v1_sessionapi_api_proto_rawDescGZIP(), []int{3}
}

type StartLoginRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Optional. The org to log in to. Required if using enterprise SSO or if
	// using a social login that belongs to more than one org.
	OrgName string `protobuf:"bytes,4,opt,name=org_name,json=orgName,proto3" json:"org_name,omitempty"`
	// Optional. A hint about which user account to authenticate with. Not all
	// IDPs support login hints.
	Hint string `protobuf:"bytes,6,opt,name=hint,proto3" json:"hint,omitempty"`
	// Optional. Whether the client supports pairing code login.
	// This field is used for temporary backward compatibility with clients that
	// do not support the pairing code login flow. In the future, this field will
	// be deprecated and pairing code login will be enforced.
	SupportsPairingCode bool `protobuf:"varint,8,opt,name=supports_pairing_code,json=supportsPairingCode,proto3" json:"supports_pairing_code,omitempty"`
}

func (x *StartLoginRequest) Reset() {
	*x = StartLoginRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_v1_sessionapi_api_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StartLoginRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartLoginRequest) ProtoMessage() {}

func (x *StartLoginRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_sessionapi_api_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartLoginRequest.ProtoReflect.Descriptor instead.
func (*StartLoginRequest) Descriptor() ([]byte, []int) {
	return file_api_v1_sessionapi_api_proto_rawDescGZIP(), []int{4}
}

func (x *StartLoginRequest) GetOrgName() string {
	if x != nil {
		return x.OrgName
	}
	return ""
}

func (x *StartLoginRequest) GetHint() string {
	if x != nil {
		return x.Hint
	}
	return ""
}

func (x *StartLoginRequest) GetSupportsPairingCode() bool {
	if x != nil {
		return x.SupportsPairingCode
	}
	return false
}

type StartLoginResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// The URL to open in a browser to complete the login session with SPIRL
	// Cloud.
	LoginUrl string `protobuf:"bytes,1,opt,name=login_url,json=loginUrl,proto3" json:"login_url,omitempty"`
	// The pairing code to use for pairing the CLI with the browser.
	PairingCode string `protobuf:"bytes,2,opt,name=pairing_code,json=pairingCode,proto3" json:"pairing_code,omitempty"`
}

func (x *StartLoginResponse) Reset() {
	*x = StartLoginResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_v1_sessionapi_api_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StartLoginResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartLoginResponse) ProtoMessage() {}

func (x *StartLoginResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_sessionapi_api_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartLoginResponse.ProtoReflect.Descriptor instead.
func (*StartLoginResponse) Descriptor() ([]byte, []int) {
	return file_api_v1_sessionapi_api_proto_rawDescGZIP(), []int{5}
}

func (x *StartLoginResponse) GetLoginUrl() string {
	if x != nil {
		return x.LoginUrl
	}
	return ""
}

func (x *StartLoginResponse) GetPairingCode() string {
	if x != nil {
		return x.PairingCode
	}
	return ""
}

type ChooseOrgRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	OrgName string `protobuf:"bytes,1,opt,name=org_name,json=orgName,proto3" json:"org_name,omitempty"`
}

func (x *ChooseOrgRequest) Reset() {
	*x = ChooseOrgRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_v1_sessionapi_api_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ChooseOrgRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChooseOrgRequest) ProtoMessage() {}

func (x *ChooseOrgRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_sessionapi_api_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChooseOrgRequest.ProtoReflect.Descriptor instead.
func (*ChooseOrgRequest) Descriptor() ([]byte, []int) {
	return file_api_v1_sessionapi_api_proto_rawDescGZIP(), []int{6}
}

func (x *ChooseOrgRequest) GetOrgName() string {
	if x != nil {
		return x.OrgName
	}
	return ""
}

type ChooseOrgResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Orgs []string `protobuf:"bytes,1,rep,name=orgs,proto3" json:"orgs,omitempty"`
}

func (x *ChooseOrgResponse) Reset() {
	*x = ChooseOrgResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_v1_sessionapi_api_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ChooseOrgResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChooseOrgResponse) ProtoMessage() {}

func (x *ChooseOrgResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_sessionapi_api_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChooseOrgResponse.ProtoReflect.Descriptor instead.
func (*ChooseOrgResponse) Descriptor() ([]byte, []int) {
	return file_api_v1_sessionapi_api_proto_rawDescGZIP(), []int{7}
}

func (x *ChooseOrgResponse) GetOrgs() []string {
	if x != nil {
		return x.Orgs
	}
	return nil
}

type FinishLoginRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *FinishLoginRequest) Reset() {
	*x = FinishLoginRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_v1_sessionapi_api_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FinishLoginRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FinishLoginRequest) ProtoMessage() {}

func (x *FinishLoginRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_sessionapi_api_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FinishLoginRequest.ProtoReflect.Descriptor instead.
func (*FinishLoginRequest) Descriptor() ([]byte, []int) {
	return file_api_v1_sessionapi_api_proto_rawDescGZIP(), []int{8}
}

type FinishLoginResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// The token for the caller to use to authenticate future requests.
	Token string `protobuf:"bytes,3,opt,name=token,proto3" json:"token,omitempty"`
}

func (x *FinishLoginResponse) Reset() {
	*x = FinishLoginResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_v1_sessionapi_api_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FinishLoginResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FinishLoginResponse) ProtoMessage() {}

func (x *FinishLoginResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_sessionapi_api_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FinishLoginResponse.ProtoReflect.Descriptor instead.
func (*FinishLoginResponse) Descriptor() ([]byte, []int) {
	return file_api_v1_sessionapi_api_proto_rawDescGZIP(), []int{9}
}

func (x *FinishLoginResponse) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

type WhoamiRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *WhoamiRequest) Reset() {
	*x = WhoamiRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_v1_sessionapi_api_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WhoamiRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WhoamiRequest) ProtoMessage() {}

func (x *WhoamiRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_sessionapi_api_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WhoamiRequest.ProtoReflect.Descriptor instead.
func (*WhoamiRequest) Descriptor() ([]byte, []int) {
	return file_api_v1_sessionapi_api_proto_rawDescGZIP(), []int{10}
}

type WhoamiResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// The org the identity belongs to.
	OrgName string `protobuf:"bytes,1,opt,name=org_name,json=orgName,proto3" json:"org_name,omitempty"`
	// The identity information.
	//
	// Types that are assignable to Identity:
	//
	//	*WhoamiResponse_User
	//	*WhoamiResponse_ServiceAccount
	Identity isWhoamiResponse_Identity `protobuf_oneof:"identity"`
	// The org role of the identity.
	OrgRole *OrgRole `protobuf:"bytes,4,opt,name=org_role,json=orgRole,proto3" json:"org_role,omitempty"`
}

func (x *WhoamiResponse) Reset() {
	*x = WhoamiResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_v1_sessionapi_api_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WhoamiResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WhoamiResponse) ProtoMessage() {}

func (x *WhoamiResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_sessionapi_api_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WhoamiResponse.ProtoReflect.Descriptor instead.
func (*WhoamiResponse) Descriptor() ([]byte, []int) {
	return file_api_v1_sessionapi_api_proto_rawDescGZIP(), []int{11}
}

func (x *WhoamiResponse) GetOrgName() string {
	if x != nil {
		return x.OrgName
	}
	return ""
}

func (m *WhoamiResponse) GetIdentity() isWhoamiResponse_Identity {
	if m != nil {
		return m.Identity
	}
	return nil
}

func (x *WhoamiResponse) GetUser() *User {
	if x, ok := x.GetIdentity().(*WhoamiResponse_User); ok {
		return x.User
	}
	return nil
}

func (x *WhoamiResponse) GetServiceAccount() *ServiceAccount {
	if x, ok := x.GetIdentity().(*WhoamiResponse_ServiceAccount); ok {
		return x.ServiceAccount
	}
	return nil
}

func (x *WhoamiResponse) GetOrgRole() *OrgRole {
	if x != nil {
		return x.OrgRole
	}
	return nil
}

type isWhoamiResponse_Identity interface {
	isWhoamiResponse_Identity()
}

type WhoamiResponse_User struct {
	User *User `protobuf:"bytes,2,opt,name=user,proto3,oneof"`
}

type WhoamiResponse_ServiceAccount struct {
	ServiceAccount *ServiceAccount `protobuf:"bytes,3,opt,name=service_account,json=serviceAccount,proto3,oneof"`
}

func (*WhoamiResponse_User) isWhoamiResponse_Identity() {}

func (*WhoamiResponse_ServiceAccount) isWhoamiResponse_Identity() {}

type User struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// The user's name.
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// The user's email address.
	Email string `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	// User's ID.
	Id string `protobuf:"bytes,3,opt,name=id,proto3" json:"id,omitempty"`
	// SSO provider.
	SsoProvider string `protobuf:"bytes,4,opt,name=sso_provider,json=ssoProvider,proto3" json:"sso_provider,omitempty"`
}

func (x *User) Reset() {
	*x = User{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_v1_sessionapi_api_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *User) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*User) ProtoMessage() {}

func (x *User) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_sessionapi_api_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use User.ProtoReflect.Descriptor instead.
func (*User) Descriptor() ([]byte, []int) {
	return file_api_v1_sessionapi_api_proto_rawDescGZIP(), []int{12}
}

func (x *User) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *User) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *User) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *User) GetSsoProvider() string {
	if x != nil {
		return x.SsoProvider
	}
	return ""
}

type ServiceAccount struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// The service account's name.
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// The service account's description.
	Description string `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	// The service account's authentication method.
	//
	// Types that are assignable to AuthenticationMethod:
	//
	//	*ServiceAccount_ServiceAccountKey
	AuthenticationMethod isServiceAccount_AuthenticationMethod `protobuf_oneof:"authentication_method"`
}

func (x *ServiceAccount) Reset() {
	*x = ServiceAccount{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_v1_sessionapi_api_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ServiceAccount) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServiceAccount) ProtoMessage() {}

func (x *ServiceAccount) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_sessionapi_api_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServiceAccount.ProtoReflect.Descriptor instead.
func (*ServiceAccount) Descriptor() ([]byte, []int) {
	return file_api_v1_sessionapi_api_proto_rawDescGZIP(), []int{13}
}

func (x *ServiceAccount) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ServiceAccount) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (m *ServiceAccount) GetAuthenticationMethod() isServiceAccount_AuthenticationMethod {
	if m != nil {
		return m.AuthenticationMethod
	}
	return nil
}

func (x *ServiceAccount) GetServiceAccountKey() *ServiceAccountKey {
	if x, ok := x.GetAuthenticationMethod().(*ServiceAccount_ServiceAccountKey); ok {
		return x.ServiceAccountKey
	}
	return nil
}

type isServiceAccount_AuthenticationMethod interface {
	isServiceAccount_AuthenticationMethod()
}

type ServiceAccount_ServiceAccountKey struct {
	ServiceAccountKey *ServiceAccountKey `protobuf:"bytes,3,opt,name=service_account_key,json=serviceAccountKey,proto3,oneof"`
}

func (*ServiceAccount_ServiceAccountKey) isServiceAccount_AuthenticationMethod() {}

type ServiceAccountKey struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// The ID of the service account key.
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *ServiceAccountKey) Reset() {
	*x = ServiceAccountKey{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_v1_sessionapi_api_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ServiceAccountKey) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServiceAccountKey) ProtoMessage() {}

func (x *ServiceAccountKey) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_sessionapi_api_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServiceAccountKey.ProtoReflect.Descriptor instead.
func (*ServiceAccountKey) Descriptor() ([]byte, []int) {
	return file_api_v1_sessionapi_api_proto_rawDescGZIP(), []int{14}
}

func (x *ServiceAccountKey) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type AuthenticateServiceAccountRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Request:
	//
	//	*AuthenticateServiceAccountRequest_Login
	//	*AuthenticateServiceAccountRequest_Authorization
	Request isAuthenticateServiceAccountRequest_Request `protobuf_oneof:"request"`
}

func (x *AuthenticateServiceAccountRequest) Reset() {
	*x = AuthenticateServiceAccountRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_v1_sessionapi_api_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AuthenticateServiceAccountRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthenticateServiceAccountRequest) ProtoMessage() {}

func (x *AuthenticateServiceAccountRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_sessionapi_api_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthenticateServiceAccountRequest.ProtoReflect.Descriptor instead.
func (*AuthenticateServiceAccountRequest) Descriptor() ([]byte, []int) {
	return file_api_v1_sessionapi_api_proto_rawDescGZIP(), []int{15}
}

func (m *AuthenticateServiceAccountRequest) GetRequest() isAuthenticateServiceAccountRequest_Request {
	if m != nil {
		return m.Request
	}
	return nil
}

func (x *AuthenticateServiceAccountRequest) GetLogin() *ServiceAccountKeyLogin {
	if x, ok := x.GetRequest().(*AuthenticateServiceAccountRequest_Login); ok {
		return x.Login
	}
	return nil
}

func (x *AuthenticateServiceAccountRequest) GetAuthorization() *ServiceAccountKeyAuthorization {
	if x, ok := x.GetRequest().(*AuthenticateServiceAccountRequest_Authorization); ok {
		return x.Authorization
	}
	return nil
}

type isAuthenticateServiceAccountRequest_Request interface {
	isAuthenticateServiceAccountRequest_Request()
}

type AuthenticateServiceAccountRequest_Login struct {
	Login *ServiceAccountKeyLogin `protobuf:"bytes,1,opt,name=login,proto3,oneof"`
}

type AuthenticateServiceAccountRequest_Authorization struct {
	Authorization *ServiceAccountKeyAuthorization `protobuf:"bytes,2,opt,name=authorization,proto3,oneof"`
}

func (*AuthenticateServiceAccountRequest_Login) isAuthenticateServiceAccountRequest_Request() {}

func (*AuthenticateServiceAccountRequest_Authorization) isAuthenticateServiceAccountRequest_Request() {
}

type ServiceAccountKeyLogin struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Required. The ID of the service account key the client wants to login with.
	KeyId string `protobuf:"bytes,1,opt,name=key_id,json=keyId,proto3" json:"key_id,omitempty"`
}

func (x *ServiceAccountKeyLogin) Reset() {
	*x = ServiceAccountKeyLogin{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_v1_sessionapi_api_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ServiceAccountKeyLogin) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServiceAccountKeyLogin) ProtoMessage() {}

func (x *ServiceAccountKeyLogin) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_sessionapi_api_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServiceAccountKeyLogin.ProtoReflect.Descriptor instead.
func (*ServiceAccountKeyLogin) Descriptor() ([]byte, []int) {
	return file_api_v1_sessionapi_api_proto_rawDescGZIP(), []int{16}
}

func (x *ServiceAccountKeyLogin) GetKeyId() string {
	if x != nil {
		return x.KeyId
	}
	return ""
}

type ServiceAccountKeyAuthorization struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Required. The service account key proof.
	ServiceAccountKeyProof *ServiceAccountKeyProof `protobuf:"bytes,1,opt,name=service_account_key_proof,json=serviceAccountKeyProof,proto3" json:"service_account_key_proof,omitempty"`
}

func (x *ServiceAccountKeyAuthorization) Reset() {
	*x = ServiceAccountKeyAuthorization{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_v1_sessionapi_api_proto_msgTypes[17]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ServiceAccountKeyAuthorization) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServiceAccountKeyAuthorization) ProtoMessage() {}

func (x *ServiceAccountKeyAuthorization) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_sessionapi_api_proto_msgTypes[17]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServiceAccountKeyAuthorization.ProtoReflect.Descriptor instead.
func (*ServiceAccountKeyAuthorization) Descriptor() ([]byte, []int) {
	return file_api_v1_sessionapi_api_proto_rawDescGZIP(), []int{17}
}

func (x *ServiceAccountKeyAuthorization) GetServiceAccountKeyProof() *ServiceAccountKeyProof {
	if x != nil {
		return x.ServiceAccountKeyProof
	}
	return nil
}

type ServiceAccountKeyProof struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Required. The signature of the key proof hash using the service account
	// private key.
	Signature []byte `protobuf:"bytes,1,opt,name=signature,proto3" json:"signature,omitempty"`
	// Required. The nonce incorporated into the key proof hash.
	Nonce []byte `protobuf:"bytes,2,opt,name=nonce,proto3" json:"nonce,omitempty"`
}

func (x *ServiceAccountKeyProof) Reset() {
	*x = ServiceAccountKeyProof{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_v1_sessionapi_api_proto_msgTypes[18]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ServiceAccountKeyProof) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServiceAccountKeyProof) ProtoMessage() {}

func (x *ServiceAccountKeyProof) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_sessionapi_api_proto_msgTypes[18]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServiceAccountKeyProof.ProtoReflect.Descriptor instead.
func (*ServiceAccountKeyProof) Descriptor() ([]byte, []int) {
	return file_api_v1_sessionapi_api_proto_rawDescGZIP(), []int{18}
}

func (x *ServiceAccountKeyProof) GetSignature() []byte {
	if x != nil {
		return x.Signature
	}
	return nil
}

func (x *ServiceAccountKeyProof) GetNonce() []byte {
	if x != nil {
		return x.Nonce
	}
	return nil
}

type AuthenticateServiceAccountResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Response:
	//
	//	*AuthenticateServiceAccountResponse_Challenge
	//	*AuthenticateServiceAccountResponse_Session
	Response isAuthenticateServiceAccountResponse_Response `protobuf_oneof:"response"`
}

func (x *AuthenticateServiceAccountResponse) Reset() {
	*x = AuthenticateServiceAccountResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_v1_sessionapi_api_proto_msgTypes[19]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AuthenticateServiceAccountResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthenticateServiceAccountResponse) ProtoMessage() {}

func (x *AuthenticateServiceAccountResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_sessionapi_api_proto_msgTypes[19]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthenticateServiceAccountResponse.ProtoReflect.Descriptor instead.
func (*AuthenticateServiceAccountResponse) Descriptor() ([]byte, []int) {
	return file_api_v1_sessionapi_api_proto_rawDescGZIP(), []int{19}
}

func (m *AuthenticateServiceAccountResponse) GetResponse() isAuthenticateServiceAccountResponse_Response {
	if m != nil {
		return m.Response
	}
	return nil
}

func (x *AuthenticateServiceAccountResponse) GetChallenge() *SessionChallenge {
	if x, ok := x.GetResponse().(*AuthenticateServiceAccountResponse_Challenge); ok {
		return x.Challenge
	}
	return nil
}

func (x *AuthenticateServiceAccountResponse) GetSession() *SessionInfo {
	if x, ok := x.GetResponse().(*AuthenticateServiceAccountResponse_Session); ok {
		return x.Session
	}
	return nil
}

type isAuthenticateServiceAccountResponse_Response interface {
	isAuthenticateServiceAccountResponse_Response()
}

type AuthenticateServiceAccountResponse_Challenge struct {
	Challenge *SessionChallenge `protobuf:"bytes,1,opt,name=challenge,proto3,oneof"`
}

type AuthenticateServiceAccountResponse_Session struct {
	Session *SessionInfo `protobuf:"bytes,2,opt,name=session,proto3,oneof"`
}

func (*AuthenticateServiceAccountResponse_Challenge) isAuthenticateServiceAccountResponse_Response() {
}

func (*AuthenticateServiceAccountResponse_Session) isAuthenticateServiceAccountResponse_Response() {}

type ListOrgsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ListOrgsRequest) Reset() {
	*x = ListOrgsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_v1_sessionapi_api_proto_msgTypes[20]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListOrgsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListOrgsRequest) ProtoMessage() {}

func (x *ListOrgsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_sessionapi_api_proto_msgTypes[20]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListOrgsRequest.ProtoReflect.Descriptor instead.
func (*ListOrgsRequest) Descriptor() ([]byte, []int) {
	return file_api_v1_sessionapi_api_proto_rawDescGZIP(), []int{20}
}

type ListOrgsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Orgs []*Org `protobuf:"bytes,1,rep,name=orgs,proto3" json:"orgs,omitempty"`
}

func (x *ListOrgsResponse) Reset() {
	*x = ListOrgsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_v1_sessionapi_api_proto_msgTypes[21]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListOrgsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListOrgsResponse) ProtoMessage() {}

func (x *ListOrgsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_sessionapi_api_proto_msgTypes[21]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListOrgsResponse.ProtoReflect.Descriptor instead.
func (*ListOrgsResponse) Descriptor() ([]byte, []int) {
	return file_api_v1_sessionapi_api_proto_rawDescGZIP(), []int{21}
}

func (x *ListOrgsResponse) GetOrgs() []*Org {
	if x != nil {
		return x.Orgs
	}
	return nil
}

type SessionChallenge struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// The server nonce to be incorporated into the key proof hash.
	ServerNonce []byte `protobuf:"bytes,1,opt,name=server_nonce,json=serverNonce,proto3" json:"server_nonce,omitempty"`
}

func (x *SessionChallenge) Reset() {
	*x = SessionChallenge{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_v1_sessionapi_api_proto_msgTypes[22]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SessionChallenge) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SessionChallenge) ProtoMessage() {}

func (x *SessionChallenge) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_sessionapi_api_proto_msgTypes[22]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SessionChallenge.ProtoReflect.Descriptor instead.
func (*SessionChallenge) Descriptor() ([]byte, []int) {
	return file_api_v1_sessionapi_api_proto_rawDescGZIP(), []int{22}
}

func (x *SessionChallenge) GetServerNonce() []byte {
	if x != nil {
		return x.ServerNonce
	}
	return nil
}

type SessionInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// The token for the caller to use to authenticate future requests.
	Token string `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
}

func (x *SessionInfo) Reset() {
	*x = SessionInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_v1_sessionapi_api_proto_msgTypes[23]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SessionInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SessionInfo) ProtoMessage() {}

func (x *SessionInfo) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_sessionapi_api_proto_msgTypes[23]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SessionInfo.ProtoReflect.Descriptor instead.
func (*SessionInfo) Descriptor() ([]byte, []int) {
	return file_api_v1_sessionapi_api_proto_rawDescGZIP(), []int{23}
}

func (x *SessionInfo) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

type OrgRole struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// The ID of the organization role.
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// The name of the organization role.
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *OrgRole) Reset() {
	*x = OrgRole{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_v1_sessionapi_api_proto_msgTypes[24]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OrgRole) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrgRole) ProtoMessage() {}

func (x *OrgRole) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_sessionapi_api_proto_msgTypes[24]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrgRole.ProtoReflect.Descriptor instead.
func (*OrgRole) Descriptor() ([]byte, []int) {
	return file_api_v1_sessionapi_api_proto_rawDescGZIP(), []int{24}
}

func (x *OrgRole) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *OrgRole) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type Org struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id   string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *Org) Reset() {
	*x = Org{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_v1_sessionapi_api_proto_msgTypes[25]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Org) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Org) ProtoMessage() {}

func (x *Org) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_sessionapi_api_proto_msgTypes[25]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Org.ProtoReflect.Descriptor instead.
func (*Org) Descriptor() ([]byte, []int) {
	return file_api_v1_sessionapi_api_proto_rawDescGZIP(), []int{25}
}

func (x *Org) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Org) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

var File_api_v1_sessionapi_api_proto protoreflect.FileDescriptor

var file_api_v1_sessionapi_api_proto_rawDesc = []byte{
	0x0a, 0x1b, 0x61, 0x70, 0x69, 0x2f, 0x76, 0x31, 0x2f, 0x73, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e,
	0x61, 0x70, 0x69, 0x2f, 0x61, 0x70, 0x69, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x18, 0x63,
	0x6f, 0x6d, 0x2e, 0x73, 0x70, 0x69, 0x72, 0x6c, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x76, 0x31, 0x2e,
	0x73, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x22, 0xf3, 0x01, 0x0a, 0x0c, 0x4c, 0x6f, 0x67, 0x69,
	0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x43, 0x0a, 0x05, 0x73, 0x74, 0x61, 0x72,
	0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x2b, 0x2e, 0x63, 0x6f, 0x6d, 0x2e, 0x73, 0x70,
	0x69, 0x72, 0x6c, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x76, 0x31, 0x2e, 0x73, 0x65, 0x73, 0x73, 0x69,
	0x6f, 0x6e, 0x2e, 0x53, 0x74, 0x61, 0x72, 0x74, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x48, 0x00, 0x52, 0x05, 0x73, 0x74, 0x61, 0x72, 0x74, 0x12, 0x46, 0x0a,
	0x06, 0x66, 0x69, 0x6e, 0x69, 0x73, 0x68, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x2c, 0x2e,
	0x63, 0x6f, 0x6d, 0x2e, 0x73, 0x70, 0x69, 0x72, 0x6c, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x76, 0x31,
	0x2e, 0x73, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x2e, 0x46, 0x69, 0x6e, 0x69, 0x73, 0x68, 0x4c,
	0x6f, 0x67, 0x69, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x48, 0x00, 0x52, 0x06, 0x66,
	0x69, 0x6e, 0x69, 0x73, 0x68, 0x12, 0x4b, 0x0a, 0x0a, 0x63, 0x68, 0x6f, 0x6f, 0x73, 0x65, 0x5f,
	0x6f, 0x72, 0x67, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x2a, 0x2e, 0x63, 0x6f, 0x6d, 0x2e,
	0x73, 0x70, 0x69, 0x72, 0x6c, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x76, 0x31, 0x2e, 0x73, 0x65, 0x73,
	0x73, 0x69, 0x6f, 0x6e, 0x2e, 0x43, 0x68, 0x6f, 0x6f, 0x73, 0x65, 0x4f, 0x72, 0x67, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x48, 0x00, 0x52, 0x09, 0x63, 0x68, 0x6f, 0x6f, 0x73, 0x65, 0x4f,
	0x72, 0x67, 0x42, 0x09, 0x0a, 0x07, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0xf8, 0x01,
	0x0a, 0x0d, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x44, 0x0a, 0x05, 0x73, 0x74, 0x61, 0x72, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x2c,
	0x2e, 0x63, 0x6f, 0x6d, 0x2e, 0x73, 0x70, 0x69, 0x72, 0x6c, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x76,
	0x31, 0x2e, 0x73, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x2e, 0x53, 0x74, 0x61, 0x72, 0x74, 0x4c,
	0x6f, 0x67, 0x69, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x48, 0x00, 0x52, 0x05,
	0x73, 0x74, 0x61, 0x72, 0x74, 0x12, 0x47, 0x0a, 0x06, 0x66, 0x69, 0x6e, 0x69, 0x73, 0x68, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x2d, 0x2e, 0x63, 0x6f, 0x6d, 0x2e, 0x73, 0x70, 0x69, 0x72,
	0x6c, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x76, 0x31, 0x2e, 0x73, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e,
	0x2e, 0x46, 0x69, 0x6e, 0x69, 0x73, 0x68, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x48, 0x00, 0x52, 0x06, 0x66, 0x69, 0x6e, 0x69, 0x73, 0x68, 0x12, 0x4c,
	0x0a, 0x0a, 0x63, 0x68, 0x6f, 0x6f, 0x73, 0x65, 0x5f, 0x6f, 0x72, 0x67, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x2b, 0x2e, 0x63, 0x6f, 0x6d, 0x2e, 0x73, 0x70, 0x69, 0x72, 0x6c, 0x2e, 0x61,
	0x70, 0x69, 0x2e, 0x76, 0x31, 0x2e, 0x73, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x2e, 0x43, 0x68,
	0x6f, 0x6f, 0x73, 0x65, 0x4f, 0x72, 0x67, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x48,
	0x00, 0x52, 0x09, 0x63, 0x68, 0x6f, 0x6f, 0x73, 0x65, 0x4f, 0x72, 0x67, 0x42, 0x0a, 0x0a, 0x08,
	0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x0f, 0x0a, 0x0d, 0x4c, 0x6f, 0x67, 0x6f,
	0x75, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x10, 0x0a, 0x0e, 0x4c, 0x6f, 0x67,
	0x6f, 0x75, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x94, 0x01, 0x0a, 0x11,
	0x53, 0x74, 0x61, 0x72, 0x74, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x19, 0x0a, 0x08, 0x6f, 0x72, 0x67, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x04, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x07, 0x6f, 0x72, 0x67, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x12, 0x0a, 0x04,
	0x68, 0x69, 0x6e, 0x74, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x68, 0x69, 0x6e, 0x74,
	0x12, 0x32, 0x0a, 0x15, 0x73, 0x75, 0x70, 0x70, 0x6f, 0x72, 0x74, 0x73, 0x5f, 0x70, 0x61, 0x69,
	0x72, 0x69, 0x6e, 0x67, 0x5f, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x08, 0x20, 0x01, 0x28, 0x08, 0x52,
	0x13, 0x73, 0x75, 0x70, 0x70, 0x6f, 0x72, 0x74, 0x73, 0x50, 0x61, 0x69, 0x72, 0x69, 0x6e, 0x67,
	0x43, 0x6f, 0x64, 0x65, 0x4a, 0x04, 0x08, 0x01, 0x10, 0x02, 0x4a, 0x04, 0x08, 0x02, 0x10, 0x03,
	0x4a, 0x04, 0x08, 0x03, 0x10, 0x04, 0x4a, 0x04, 0x08, 0x07, 0x10, 0x08, 0x4a, 0x04, 0x08, 0x05,
	0x10, 0x06, 0x22, 0x54, 0x0a, 0x12, 0x53, 0x74, 0x61, 0x72, 0x74, 0x4c, 0x6f, 0x67, 0x69, 0x6e,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1b, 0x0a, 0x09, 0x6c, 0x6f, 0x67, 0x69,
	0x6e, 0x5f, 0x75, 0x72, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x6c, 0x6f, 0x67,
	0x69, 0x6e, 0x55, 0x72, 0x6c, 0x12, 0x21, 0x0a, 0x0c, 0x70, 0x61, 0x69, 0x72, 0x69, 0x6e, 0x67,
	0x5f, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x70, 0x61, 0x69,
	0x72, 0x69, 0x6e, 0x67, 0x43, 0x6f, 0x64, 0x65, 0x22, 0x2d, 0x0a, 0x10, 0x43, 0x68, 0x6f, 0x6f,
	0x73, 0x65, 0x4f, 0x72, 0x67, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x19, 0x0a, 0x08,
	0x6f, 0x72, 0x67, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07,
	0x6f, 0x72, 0x67, 0x4e, 0x61, 0x6d, 0x65, 0x22, 0x27, 0x0a, 0x11, 0x43, 0x68, 0x6f, 0x6f, 0x73,
	0x65, 0x4f, 0x72, 0x67, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x12, 0x0a, 0x04,
	0x6f, 0x72, 0x67, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x09, 0x52, 0x04, 0x6f, 0x72, 0x67, 0x73,
	0x22, 0x1a, 0x0a, 0x12, 0x46, 0x69, 0x6e, 0x69, 0x73, 0x68, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x4a, 0x04, 0x08, 0x01, 0x10, 0x02, 0x22, 0x37, 0x0a, 0x13,
	0x46, 0x69, 0x6e, 0x69, 0x73, 0x68, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x4a, 0x04, 0x08, 0x01, 0x10, 0x02, 0x4a,
	0x04, 0x08, 0x02, 0x10, 0x03, 0x22, 0x0f, 0x0a, 0x0d, 0x57, 0x68, 0x6f, 0x61, 0x6d, 0x69, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x80, 0x02, 0x0a, 0x0e, 0x57, 0x68, 0x6f, 0x61, 0x6d,
	0x69, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x19, 0x0a, 0x08, 0x6f, 0x72, 0x67,
	0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6f, 0x72, 0x67,
	0x4e, 0x61, 0x6d, 0x65, 0x12, 0x34, 0x0a, 0x04, 0x75, 0x73, 0x65, 0x72, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x1e, 0x2e, 0x63, 0x6f, 0x6d, 0x2e, 0x73, 0x70, 0x69, 0x72, 0x6c, 0x2e, 0x61,
	0x70, 0x69, 0x2e, 0x76, 0x31, 0x2e, 0x73, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x2e, 0x55, 0x73,
	0x65, 0x72, 0x48, 0x00, 0x52, 0x04, 0x75, 0x73, 0x65, 0x72, 0x12, 0x53, 0x0a, 0x0f, 0x73, 0x65,
	0x72, 0x76, 0x69, 0x63, 0x65, 0x5f, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x28, 0x2e, 0x63, 0x6f, 0x6d, 0x2e, 0x73, 0x70, 0x69, 0x72, 0x6c, 0x2e,
	0x61, 0x70, 0x69, 0x2e, 0x76, 0x31, 0x2e, 0x73, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x2e, 0x53,
	0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x48, 0x00, 0x52,
	0x0e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x12,
	0x3c, 0x0a, 0x08, 0x6f, 0x72, 0x67, 0x5f, 0x72, 0x6f, 0x6c, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x21, 0x2e, 0x63, 0x6f, 0x6d, 0x2e, 0x73, 0x70, 0x69, 0x72, 0x6c, 0x2e, 0x61, 0x70,
	0x69, 0x2e, 0x76, 0x31, 0x2e, 0x73, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x2e, 0x4f, 0x72, 0x67,
	0x52, 0x6f, 0x6c, 0x65, 0x52, 0x07, 0x6f, 0x72, 0x67, 0x52, 0x6f, 0x6c, 0x65, 0x42, 0x0a, 0x0a,
	0x08, 0x69, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x22, 0x63, 0x0a, 0x04, 0x55, 0x73, 0x65,
	0x72, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x65, 0x6d, 0x61, 0x69, 0x6c, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x65, 0x6d, 0x61, 0x69, 0x6c, 0x12, 0x0e, 0x0a, 0x02, 0x69,
	0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x21, 0x0a, 0x0c, 0x73,
	0x73, 0x6f, 0x5f, 0x70, 0x72, 0x6f, 0x76, 0x69, 0x64, 0x65, 0x72, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x0b, 0x73, 0x73, 0x6f, 0x50, 0x72, 0x6f, 0x76, 0x69, 0x64, 0x65, 0x72, 0x22, 0xbe,
	0x01, 0x0a, 0x0e, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e,
	0x74, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x20, 0x0a, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70,
	0x74, 0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x64, 0x65, 0x73, 0x63,
	0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x5d, 0x0a, 0x13, 0x73, 0x65, 0x72, 0x76, 0x69,
	0x63, 0x65, 0x5f, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x5f, 0x6b, 0x65, 0x79, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x2b, 0x2e, 0x63, 0x6f, 0x6d, 0x2e, 0x73, 0x70, 0x69, 0x72, 0x6c,
	0x2e, 0x61, 0x70, 0x69, 0x2e, 0x76, 0x31, 0x2e, 0x73, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x2e,
	0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x4b, 0x65,
	0x79, 0x48, 0x00, 0x52, 0x11, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x41, 0x63, 0x63, 0x6f,
	0x75, 0x6e, 0x74, 0x4b, 0x65, 0x79, 0x42, 0x17, 0x0a, 0x15, 0x61, 0x75, 0x74, 0x68, 0x65, 0x6e,
	0x74, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x6d, 0x65, 0x74, 0x68, 0x6f, 0x64, 0x22,
	0x23, 0x0a, 0x11, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e,
	0x74, 0x4b, 0x65, 0x79, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x02, 0x69, 0x64, 0x22, 0xda, 0x01, 0x0a, 0x21, 0x41, 0x75, 0x74, 0x68, 0x65, 0x6e, 0x74,
	0x69, 0x63, 0x61, 0x74, 0x65, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x41, 0x63, 0x63, 0x6f,
	0x75, 0x6e, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x48, 0x0a, 0x05, 0x6c, 0x6f,
	0x67, 0x69, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x30, 0x2e, 0x63, 0x6f, 0x6d, 0x2e,
	0x73, 0x70, 0x69, 0x72, 0x6c, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x76, 0x31, 0x2e, 0x73, 0x65, 0x73,
	0x73, 0x69, 0x6f, 0x6e, 0x2e, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x41, 0x63, 0x63, 0x6f,
	0x75, 0x6e, 0x74, 0x4b, 0x65, 0x79, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x48, 0x00, 0x52, 0x05, 0x6c,
	0x6f, 0x67, 0x69, 0x6e, 0x12, 0x60, 0x0a, 0x0d, 0x61, 0x75, 0x74, 0x68, 0x6f, 0x72, 0x69, 0x7a,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x38, 0x2e, 0x63, 0x6f,
	0x6d, 0x2e, 0x73, 0x70, 0x69, 0x72, 0x6c, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x76, 0x31, 0x2e, 0x73,
	0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x2e, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x41, 0x63,
	0x63, 0x6f, 0x75, 0x6e, 0x74, 0x4b, 0x65, 0x79, 0x41, 0x75, 0x74, 0x68, 0x6f, 0x72, 0x69, 0x7a,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x48, 0x00, 0x52, 0x0d, 0x61, 0x75, 0x74, 0x68, 0x6f, 0x72, 0x69,
	0x7a, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x42, 0x09, 0x0a, 0x07, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x22, 0x2f, 0x0a, 0x16, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x41, 0x63, 0x63, 0x6f,
	0x75, 0x6e, 0x74, 0x4b, 0x65, 0x79, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x12, 0x15, 0x0a, 0x06, 0x6b,
	0x65, 0x79, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x6b, 0x65, 0x79,
	0x49, 0x64, 0x22, 0x8d, 0x01, 0x0a, 0x1e, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x41, 0x63,
	0x63, 0x6f, 0x75, 0x6e, 0x74, 0x4b, 0x65, 0x79, 0x41, 0x75, 0x74, 0x68, 0x6f, 0x72, 0x69, 0x7a,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x6b, 0x0a, 0x19, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65,
	0x5f, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x5f, 0x6b, 0x65, 0x79, 0x5f, 0x70, 0x72, 0x6f,
	0x6f, 0x66, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x30, 0x2e, 0x63, 0x6f, 0x6d, 0x2e, 0x73,
	0x70, 0x69, 0x72, 0x6c, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x76, 0x31, 0x2e, 0x73, 0x65, 0x73, 0x73,
	0x69, 0x6f, 0x6e, 0x2e, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x41, 0x63, 0x63, 0x6f, 0x75,
	0x6e, 0x74, 0x4b, 0x65, 0x79, 0x50, 0x72, 0x6f, 0x6f, 0x66, 0x52, 0x16, 0x73, 0x65, 0x72, 0x76,
	0x69, 0x63, 0x65, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x4b, 0x65, 0x79, 0x50, 0x72, 0x6f,
	0x6f, 0x66, 0x22, 0x50, 0x0a, 0x16, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x41, 0x63, 0x63,
	0x6f, 0x75, 0x6e, 0x74, 0x4b, 0x65, 0x79, 0x50, 0x72, 0x6f, 0x6f, 0x66, 0x12, 0x1e, 0x0a, 0x09,
	0x73, 0x69, 0x67, 0x6e, 0x61, 0x74, 0x75, 0x72, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x42,
	0x00, 0x52, 0x09, 0x73, 0x69, 0x67, 0x6e, 0x61, 0x74, 0x75, 0x72, 0x65, 0x12, 0x16, 0x0a, 0x05,
	0x6e, 0x6f, 0x6e, 0x63, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x42, 0x00, 0x52, 0x05, 0x6e,
	0x6f, 0x6e, 0x63, 0x65, 0x22, 0xbf, 0x01, 0x0a, 0x22, 0x41, 0x75, 0x74, 0x68, 0x65, 0x6e, 0x74,
	0x69, 0x63, 0x61, 0x74, 0x65, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x41, 0x63, 0x63, 0x6f,
	0x75, 0x6e, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x4a, 0x0a, 0x09, 0x63,
	0x68, 0x61, 0x6c, 0x6c, 0x65, 0x6e, 0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x2a,
	0x2e, 0x63, 0x6f, 0x6d, 0x2e, 0x73, 0x70, 0x69, 0x72, 0x6c, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x76,
	0x31, 0x2e, 0x73, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x2e, 0x53, 0x65, 0x73, 0x73, 0x69, 0x6f,
	0x6e, 0x43, 0x68, 0x61, 0x6c, 0x6c, 0x65, 0x6e, 0x67, 0x65, 0x48, 0x00, 0x52, 0x09, 0x63, 0x68,
	0x61, 0x6c, 0x6c, 0x65, 0x6e, 0x67, 0x65, 0x12, 0x41, 0x0a, 0x07, 0x73, 0x65, 0x73, 0x73, 0x69,
	0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x25, 0x2e, 0x63, 0x6f, 0x6d, 0x2e, 0x73,
	0x70, 0x69, 0x72, 0x6c, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x76, 0x31, 0x2e, 0x73, 0x65, 0x73, 0x73,
	0x69, 0x6f, 0x6e, 0x2e, 0x53, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x49, 0x6e, 0x66, 0x6f, 0x48,
	0x00, 0x52, 0x07, 0x73, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x42, 0x0a, 0x0a, 0x08, 0x72, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x11, 0x0a, 0x0f, 0x4c, 0x69, 0x73, 0x74, 0x4f, 0x72,
	0x67, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x45, 0x0a, 0x10, 0x4c, 0x69, 0x73,
	0x74, 0x4f, 0x72, 0x67, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x31, 0x0a,
	0x04, 0x6f, 0x72, 0x67, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1d, 0x2e, 0x63, 0x6f,
	0x6d, 0x2e, 0x73, 0x70, 0x69, 0x72, 0x6c, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x76, 0x31, 0x2e, 0x73,
	0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x2e, 0x4f, 0x72, 0x67, 0x52, 0x04, 0x6f, 0x72, 0x67, 0x73,
	0x22, 0x35, 0x0a, 0x10, 0x53, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x43, 0x68, 0x61, 0x6c, 0x6c,
	0x65, 0x6e, 0x67, 0x65, 0x12, 0x21, 0x0a, 0x0c, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x5f, 0x6e,
	0x6f, 0x6e, 0x63, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x0b, 0x73, 0x65, 0x72, 0x76,
	0x65, 0x72, 0x4e, 0x6f, 0x6e, 0x63, 0x65, 0x22, 0x23, 0x0a, 0x0b, 0x53, 0x65, 0x73, 0x73, 0x69,
	0x6f, 0x6e, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x22, 0x2d, 0x0a, 0x07,
	0x4f, 0x72, 0x67, 0x52, 0x6f, 0x6c, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x22, 0x29, 0x0a, 0x03, 0x4f,
	0x72, 0x67, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02,
	0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x32, 0x9e, 0x04, 0x0a, 0x03, 0x41, 0x50, 0x49, 0x12, 0x5c,
	0x0a, 0x05, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x12, 0x26, 0x2e, 0x63, 0x6f, 0x6d, 0x2e, 0x73, 0x70,
	0x69, 0x72, 0x6c, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x76, 0x31, 0x2e, 0x73, 0x65, 0x73, 0x73, 0x69,
	0x6f, 0x6e, 0x2e, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a,
	0x27, 0x2e, 0x63, 0x6f, 0x6d, 0x2e, 0x73, 0x70, 0x69, 0x72, 0x6c, 0x2e, 0x61, 0x70, 0x69, 0x2e,
	0x76, 0x31, 0x2e, 0x73, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x2e, 0x4c, 0x6f, 0x67, 0x69, 0x6e,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x28, 0x01, 0x30, 0x01, 0x12, 0x9b, 0x01, 0x0a,
	0x1a, 0x41, 0x75, 0x74, 0x68, 0x65, 0x6e, 0x74, 0x69, 0x63, 0x61, 0x74, 0x65, 0x53, 0x65, 0x72,
	0x76, 0x69, 0x63, 0x65, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x3b, 0x2e, 0x63, 0x6f,
	0x6d, 0x2e, 0x73, 0x70, 0x69, 0x72, 0x6c, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x76, 0x31, 0x2e, 0x73,
	0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x2e, 0x41, 0x75, 0x74, 0x68, 0x65, 0x6e, 0x74, 0x69, 0x63,
	0x61, 0x74, 0x65, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e,
	0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x3c, 0x2e, 0x63, 0x6f, 0x6d, 0x2e, 0x73,
	0x70, 0x69, 0x72, 0x6c, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x76, 0x31, 0x2e, 0x73, 0x65, 0x73, 0x73,
	0x69, 0x6f, 0x6e, 0x2e, 0x41, 0x75, 0x74, 0x68, 0x65, 0x6e, 0x74, 0x69, 0x63, 0x61, 0x74, 0x65,
	0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x28, 0x01, 0x30, 0x01, 0x12, 0x5b, 0x0a, 0x06, 0x57, 0x68,
	0x6f, 0x61, 0x6d, 0x69, 0x12, 0x27, 0x2e, 0x63, 0x6f, 0x6d, 0x2e, 0x73, 0x70, 0x69, 0x72, 0x6c,
	0x2e, 0x61, 0x70, 0x69, 0x2e, 0x76, 0x31, 0x2e, 0x73, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x2e,
	0x57, 0x68, 0x6f, 0x61, 0x6d, 0x69, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x28, 0x2e,
	0x63, 0x6f, 0x6d, 0x2e, 0x73, 0x70, 0x69, 0x72, 0x6c, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x76, 0x31,
	0x2e, 0x73, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x2e, 0x57, 0x68, 0x6f, 0x61, 0x6d, 0x69, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x61, 0x0a, 0x08, 0x4c, 0x69, 0x73, 0x74, 0x4f,
	0x72, 0x67, 0x73, 0x12, 0x29, 0x2e, 0x63, 0x6f, 0x6d, 0x2e, 0x73, 0x70, 0x69, 0x72, 0x6c, 0x2e,
	0x61, 0x70, 0x69, 0x2e, 0x76, 0x31, 0x2e, 0x73, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x2e, 0x4c,
	0x69, 0x73, 0x74, 0x4f, 0x72, 0x67, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x2a,
	0x2e, 0x63, 0x6f, 0x6d, 0x2e, 0x73, 0x70, 0x69, 0x72, 0x6c, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x76,
	0x31, 0x2e, 0x73, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x4f, 0x72,
	0x67, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x5b, 0x0a, 0x06, 0x4c, 0x6f,
	0x67, 0x6f, 0x75, 0x74, 0x12, 0x27, 0x2e, 0x63, 0x6f, 0x6d, 0x2e, 0x73, 0x70, 0x69, 0x72, 0x6c,
	0x2e, 0x61, 0x70, 0x69, 0x2e, 0x76, 0x31, 0x2e, 0x73, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x2e,
	0x4c, 0x6f, 0x67, 0x6f, 0x75, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x28, 0x2e,
	0x63, 0x6f, 0x6d, 0x2e, 0x73, 0x70, 0x69, 0x72, 0x6c, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x76, 0x31,
	0x2e, 0x73, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x2e, 0x4c, 0x6f, 0x67, 0x6f, 0x75, 0x74, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x31, 0x5a, 0x2f, 0x67, 0x69, 0x74, 0x68, 0x75,
	0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x73, 0x70, 0x69, 0x72, 0x6c, 0x2f, 0x73, 0x70, 0x69, 0x72,
	0x6c, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x76, 0x31, 0x2f,
	0x73, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x61, 0x70, 0x69, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
}

var (
	file_api_v1_sessionapi_api_proto_rawDescOnce sync.Once
	file_api_v1_sessionapi_api_proto_rawDescData = file_api_v1_sessionapi_api_proto_rawDesc
)

func file_api_v1_sessionapi_api_proto_rawDescGZIP() []byte {
	file_api_v1_sessionapi_api_proto_rawDescOnce.Do(func() {
		file_api_v1_sessionapi_api_proto_rawDescData = protoimpl.X.CompressGZIP(file_api_v1_sessionapi_api_proto_rawDescData)
	})
	return file_api_v1_sessionapi_api_proto_rawDescData
}

var file_api_v1_sessionapi_api_proto_msgTypes = make([]protoimpl.MessageInfo, 26)
var file_api_v1_sessionapi_api_proto_goTypes = []any{
	(*LoginRequest)(nil),                       // 0: com.spirl.api.v1.session.LoginRequest
	(*LoginResponse)(nil),                      // 1: com.spirl.api.v1.session.LoginResponse
	(*LogoutRequest)(nil),                      // 2: com.spirl.api.v1.session.LogoutRequest
	(*LogoutResponse)(nil),                     // 3: com.spirl.api.v1.session.LogoutResponse
	(*StartLoginRequest)(nil),                  // 4: com.spirl.api.v1.session.StartLoginRequest
	(*StartLoginResponse)(nil),                 // 5: com.spirl.api.v1.session.StartLoginResponse
	(*ChooseOrgRequest)(nil),                   // 6: com.spirl.api.v1.session.ChooseOrgRequest
	(*ChooseOrgResponse)(nil),                  // 7: com.spirl.api.v1.session.ChooseOrgResponse
	(*FinishLoginRequest)(nil),                 // 8: com.spirl.api.v1.session.FinishLoginRequest
	(*FinishLoginResponse)(nil),                // 9: com.spirl.api.v1.session.FinishLoginResponse
	(*WhoamiRequest)(nil),                      // 10: com.spirl.api.v1.session.WhoamiRequest
	(*WhoamiResponse)(nil),                     // 11: com.spirl.api.v1.session.WhoamiResponse
	(*User)(nil),                               // 12: com.spirl.api.v1.session.User
	(*ServiceAccount)(nil),                     // 13: com.spirl.api.v1.session.ServiceAccount
	(*ServiceAccountKey)(nil),                  // 14: com.spirl.api.v1.session.ServiceAccountKey
	(*AuthenticateServiceAccountRequest)(nil),  // 15: com.spirl.api.v1.session.AuthenticateServiceAccountRequest
	(*ServiceAccountKeyLogin)(nil),             // 16: com.spirl.api.v1.session.ServiceAccountKeyLogin
	(*ServiceAccountKeyAuthorization)(nil),     // 17: com.spirl.api.v1.session.ServiceAccountKeyAuthorization
	(*ServiceAccountKeyProof)(nil),             // 18: com.spirl.api.v1.session.ServiceAccountKeyProof
	(*AuthenticateServiceAccountResponse)(nil), // 19: com.spirl.api.v1.session.AuthenticateServiceAccountResponse
	(*ListOrgsRequest)(nil),                    // 20: com.spirl.api.v1.session.ListOrgsRequest
	(*ListOrgsResponse)(nil),                   // 21: com.spirl.api.v1.session.ListOrgsResponse
	(*SessionChallenge)(nil),                   // 22: com.spirl.api.v1.session.SessionChallenge
	(*SessionInfo)(nil),                        // 23: com.spirl.api.v1.session.SessionInfo
	(*OrgRole)(nil),                            // 24: com.spirl.api.v1.session.OrgRole
	(*Org)(nil),                                // 25: com.spirl.api.v1.session.Org
}
var file_api_v1_sessionapi_api_proto_depIdxs = []int32{
	4,  // 0: com.spirl.api.v1.session.LoginRequest.start:type_name -> com.spirl.api.v1.session.StartLoginRequest
	8,  // 1: com.spirl.api.v1.session.LoginRequest.finish:type_name -> com.spirl.api.v1.session.FinishLoginRequest
	6,  // 2: com.spirl.api.v1.session.LoginRequest.choose_org:type_name -> com.spirl.api.v1.session.ChooseOrgRequest
	5,  // 3: com.spirl.api.v1.session.LoginResponse.start:type_name -> com.spirl.api.v1.session.StartLoginResponse
	9,  // 4: com.spirl.api.v1.session.LoginResponse.finish:type_name -> com.spirl.api.v1.session.FinishLoginResponse
	7,  // 5: com.spirl.api.v1.session.LoginResponse.choose_org:type_name -> com.spirl.api.v1.session.ChooseOrgResponse
	12, // 6: com.spirl.api.v1.session.WhoamiResponse.user:type_name -> com.spirl.api.v1.session.User
	13, // 7: com.spirl.api.v1.session.WhoamiResponse.service_account:type_name -> com.spirl.api.v1.session.ServiceAccount
	24, // 8: com.spirl.api.v1.session.WhoamiResponse.org_role:type_name -> com.spirl.api.v1.session.OrgRole
	14, // 9: com.spirl.api.v1.session.ServiceAccount.service_account_key:type_name -> com.spirl.api.v1.session.ServiceAccountKey
	16, // 10: com.spirl.api.v1.session.AuthenticateServiceAccountRequest.login:type_name -> com.spirl.api.v1.session.ServiceAccountKeyLogin
	17, // 11: com.spirl.api.v1.session.AuthenticateServiceAccountRequest.authorization:type_name -> com.spirl.api.v1.session.ServiceAccountKeyAuthorization
	18, // 12: com.spirl.api.v1.session.ServiceAccountKeyAuthorization.service_account_key_proof:type_name -> com.spirl.api.v1.session.ServiceAccountKeyProof
	22, // 13: com.spirl.api.v1.session.AuthenticateServiceAccountResponse.challenge:type_name -> com.spirl.api.v1.session.SessionChallenge
	23, // 14: com.spirl.api.v1.session.AuthenticateServiceAccountResponse.session:type_name -> com.spirl.api.v1.session.SessionInfo
	25, // 15: com.spirl.api.v1.session.ListOrgsResponse.orgs:type_name -> com.spirl.api.v1.session.Org
	0,  // 16: com.spirl.api.v1.session.API.Login:input_type -> com.spirl.api.v1.session.LoginRequest
	15, // 17: com.spirl.api.v1.session.API.AuthenticateServiceAccount:input_type -> com.spirl.api.v1.session.AuthenticateServiceAccountRequest
	10, // 18: com.spirl.api.v1.session.API.Whoami:input_type -> com.spirl.api.v1.session.WhoamiRequest
	20, // 19: com.spirl.api.v1.session.API.ListOrgs:input_type -> com.spirl.api.v1.session.ListOrgsRequest
	2,  // 20: com.spirl.api.v1.session.API.Logout:input_type -> com.spirl.api.v1.session.LogoutRequest
	1,  // 21: com.spirl.api.v1.session.API.Login:output_type -> com.spirl.api.v1.session.LoginResponse
	19, // 22: com.spirl.api.v1.session.API.AuthenticateServiceAccount:output_type -> com.spirl.api.v1.session.AuthenticateServiceAccountResponse
	11, // 23: com.spirl.api.v1.session.API.Whoami:output_type -> com.spirl.api.v1.session.WhoamiResponse
	21, // 24: com.spirl.api.v1.session.API.ListOrgs:output_type -> com.spirl.api.v1.session.ListOrgsResponse
	3,  // 25: com.spirl.api.v1.session.API.Logout:output_type -> com.spirl.api.v1.session.LogoutResponse
	21, // [21:26] is the sub-list for method output_type
	16, // [16:21] is the sub-list for method input_type
	16, // [16:16] is the sub-list for extension type_name
	16, // [16:16] is the sub-list for extension extendee
	0,  // [0:16] is the sub-list for field type_name
}

func init() { file_api_v1_sessionapi_api_proto_init() }
func file_api_v1_sessionapi_api_proto_init() {
	if File_api_v1_sessionapi_api_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_api_v1_sessionapi_api_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*LoginRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_v1_sessionapi_api_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*LoginResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_v1_sessionapi_api_proto_msgTypes[2].Exporter = func(v any, i int) any {
			switch v := v.(*LogoutRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_v1_sessionapi_api_proto_msgTypes[3].Exporter = func(v any, i int) any {
			switch v := v.(*LogoutResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_v1_sessionapi_api_proto_msgTypes[4].Exporter = func(v any, i int) any {
			switch v := v.(*StartLoginRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_v1_sessionapi_api_proto_msgTypes[5].Exporter = func(v any, i int) any {
			switch v := v.(*StartLoginResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_v1_sessionapi_api_proto_msgTypes[6].Exporter = func(v any, i int) any {
			switch v := v.(*ChooseOrgRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_v1_sessionapi_api_proto_msgTypes[7].Exporter = func(v any, i int) any {
			switch v := v.(*ChooseOrgResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_v1_sessionapi_api_proto_msgTypes[8].Exporter = func(v any, i int) any {
			switch v := v.(*FinishLoginRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_v1_sessionapi_api_proto_msgTypes[9].Exporter = func(v any, i int) any {
			switch v := v.(*FinishLoginResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_v1_sessionapi_api_proto_msgTypes[10].Exporter = func(v any, i int) any {
			switch v := v.(*WhoamiRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_v1_sessionapi_api_proto_msgTypes[11].Exporter = func(v any, i int) any {
			switch v := v.(*WhoamiResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_v1_sessionapi_api_proto_msgTypes[12].Exporter = func(v any, i int) any {
			switch v := v.(*User); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_v1_sessionapi_api_proto_msgTypes[13].Exporter = func(v any, i int) any {
			switch v := v.(*ServiceAccount); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_v1_sessionapi_api_proto_msgTypes[14].Exporter = func(v any, i int) any {
			switch v := v.(*ServiceAccountKey); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_v1_sessionapi_api_proto_msgTypes[15].Exporter = func(v any, i int) any {
			switch v := v.(*AuthenticateServiceAccountRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_v1_sessionapi_api_proto_msgTypes[16].Exporter = func(v any, i int) any {
			switch v := v.(*ServiceAccountKeyLogin); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_v1_sessionapi_api_proto_msgTypes[17].Exporter = func(v any, i int) any {
			switch v := v.(*ServiceAccountKeyAuthorization); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_v1_sessionapi_api_proto_msgTypes[18].Exporter = func(v any, i int) any {
			switch v := v.(*ServiceAccountKeyProof); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_v1_sessionapi_api_proto_msgTypes[19].Exporter = func(v any, i int) any {
			switch v := v.(*AuthenticateServiceAccountResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_v1_sessionapi_api_proto_msgTypes[20].Exporter = func(v any, i int) any {
			switch v := v.(*ListOrgsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_v1_sessionapi_api_proto_msgTypes[21].Exporter = func(v any, i int) any {
			switch v := v.(*ListOrgsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_v1_sessionapi_api_proto_msgTypes[22].Exporter = func(v any, i int) any {
			switch v := v.(*SessionChallenge); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_v1_sessionapi_api_proto_msgTypes[23].Exporter = func(v any, i int) any {
			switch v := v.(*SessionInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_v1_sessionapi_api_proto_msgTypes[24].Exporter = func(v any, i int) any {
			switch v := v.(*OrgRole); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_v1_sessionapi_api_proto_msgTypes[25].Exporter = func(v any, i int) any {
			switch v := v.(*Org); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_api_v1_sessionapi_api_proto_msgTypes[0].OneofWrappers = []any{
		(*LoginRequest_Start)(nil),
		(*LoginRequest_Finish)(nil),
		(*LoginRequest_ChooseOrg)(nil),
	}
	file_api_v1_sessionapi_api_proto_msgTypes[1].OneofWrappers = []any{
		(*LoginResponse_Start)(nil),
		(*LoginResponse_Finish)(nil),
		(*LoginResponse_ChooseOrg)(nil),
	}
	file_api_v1_sessionapi_api_proto_msgTypes[11].OneofWrappers = []any{
		(*WhoamiResponse_User)(nil),
		(*WhoamiResponse_ServiceAccount)(nil),
	}
	file_api_v1_sessionapi_api_proto_msgTypes[13].OneofWrappers = []any{
		(*ServiceAccount_ServiceAccountKey)(nil),
	}
	file_api_v1_sessionapi_api_proto_msgTypes[15].OneofWrappers = []any{
		(*AuthenticateServiceAccountRequest_Login)(nil),
		(*AuthenticateServiceAccountRequest_Authorization)(nil),
	}
	file_api_v1_sessionapi_api_proto_msgTypes[19].OneofWrappers = []any{
		(*AuthenticateServiceAccountResponse_Challenge)(nil),
		(*AuthenticateServiceAccountResponse_Session)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_api_v1_sessionapi_api_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   26,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_v1_sessionapi_api_proto_goTypes,
		DependencyIndexes: file_api_v1_sessionapi_api_proto_depIdxs,
		MessageInfos:      file_api_v1_sessionapi_api_proto_msgTypes,
	}.Build()
	File_api_v1_sessionapi_api_proto = out.File
	file_api_v1_sessionapi_api_proto_rawDesc = nil
	file_api_v1_sessionapi_api_proto_goTypes = nil
	file_api_v1_sessionapi_api_proto_depIdxs = nil
}
