// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             (unknown)
// source: api/v1/configapi/api.proto

package configapi

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	API_GetOrgConfig_FullMethodName            = "/com.spirl.api.v1.config.API/GetOrgConfig"
	API_UpdateOrgConfig_FullMethodName         = "/com.spirl.api.v1.config.API/UpdateOrgConfig"
	API_GetTrustDomainConfig_FullMethodName    = "/com.spirl.api.v1.config.API/GetTrustDomainConfig"
	API_UpdateTrustDomainConfig_FullMethodName = "/com.spirl.api.v1.config.API/UpdateTrustDomainConfig"
	API_GetClusterConfig_FullMethodName        = "/com.spirl.api.v1.config.API/GetClusterConfig"
	API_UpdateClusterConfig_FullMethodName     = "/com.spirl.api.v1.config.API/UpdateClusterConfig"
)

// APIClient is the client API for API service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type APIClient interface {
	// Gets the configuration for the org.
	GetOrgConfig(ctx context.Context, in *GetOrgConfigRequest, opts ...grpc.CallOption) (*GetOrgConfigResponse, error)
	// Updates the configuration for the organization.
	//
	// Returns:
	//
	//	INVALID_ARGUMENT    - Configuration is invalid. For schema validation
	//	                      failures, status details include a SchemaValidationError
	//	                      message.
	//	FAILED_PRECONDITION - The current version does not match the expected version.
	UpdateOrgConfig(ctx context.Context, in *UpdateOrgConfigRequest, opts ...grpc.CallOption) (*UpdateOrgConfigResponse, error)
	// Gets the configuration for the trust domain.
	GetTrustDomainConfig(ctx context.Context, in *GetTrustDomainConfigRequest, opts ...grpc.CallOption) (*GetTrustDomainConfigResponse, error)
	// Updates the configuration for the trust domain.
	//
	// Returns:
	//
	//	INVALID_ARGUMENT    - Configuration is invalid. For schema validation
	//	                      failures, status details include a SchemaValidationError
	//	                      message.
	//	FAILED_PRECONDITION - The current version does not match the expected version.
	UpdateTrustDomainConfig(ctx context.Context, in *UpdateTrustDomainConfigRequest, opts ...grpc.CallOption) (*UpdateTrustDomainConfigResponse, error)
	// Gets the configuration for the cluster.
	GetClusterConfig(ctx context.Context, in *GetClusterConfigRequest, opts ...grpc.CallOption) (*GetClusterConfigResponse, error)
	// Updates the configuration for the cluster.
	//
	// Returns:
	//
	//	INVALID_ARGUMENT    - Configuration is invalid. For schema validation
	//	                      failures, status details include a SchemaValidationError
	//	                      message.
	//	FAILED_PRECONDITION - The current version does not match the expected version.
	UpdateClusterConfig(ctx context.Context, in *UpdateClusterConfigRequest, opts ...grpc.CallOption) (*UpdateClusterConfigResponse, error)
}

type aPIClient struct {
	cc grpc.ClientConnInterface
}

func NewAPIClient(cc grpc.ClientConnInterface) APIClient {
	return &aPIClient{cc}
}

func (c *aPIClient) GetOrgConfig(ctx context.Context, in *GetOrgConfigRequest, opts ...grpc.CallOption) (*GetOrgConfigResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetOrgConfigResponse)
	err := c.cc.Invoke(ctx, API_GetOrgConfig_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aPIClient) UpdateOrgConfig(ctx context.Context, in *UpdateOrgConfigRequest, opts ...grpc.CallOption) (*UpdateOrgConfigResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateOrgConfigResponse)
	err := c.cc.Invoke(ctx, API_UpdateOrgConfig_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aPIClient) GetTrustDomainConfig(ctx context.Context, in *GetTrustDomainConfigRequest, opts ...grpc.CallOption) (*GetTrustDomainConfigResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetTrustDomainConfigResponse)
	err := c.cc.Invoke(ctx, API_GetTrustDomainConfig_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aPIClient) UpdateTrustDomainConfig(ctx context.Context, in *UpdateTrustDomainConfigRequest, opts ...grpc.CallOption) (*UpdateTrustDomainConfigResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateTrustDomainConfigResponse)
	err := c.cc.Invoke(ctx, API_UpdateTrustDomainConfig_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aPIClient) GetClusterConfig(ctx context.Context, in *GetClusterConfigRequest, opts ...grpc.CallOption) (*GetClusterConfigResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetClusterConfigResponse)
	err := c.cc.Invoke(ctx, API_GetClusterConfig_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aPIClient) UpdateClusterConfig(ctx context.Context, in *UpdateClusterConfigRequest, opts ...grpc.CallOption) (*UpdateClusterConfigResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateClusterConfigResponse)
	err := c.cc.Invoke(ctx, API_UpdateClusterConfig_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// APIServer is the server API for API service.
// All implementations must embed UnimplementedAPIServer
// for forward compatibility.
type APIServer interface {
	// Gets the configuration for the org.
	GetOrgConfig(context.Context, *GetOrgConfigRequest) (*GetOrgConfigResponse, error)
	// Updates the configuration for the organization.
	//
	// Returns:
	//
	//	INVALID_ARGUMENT    - Configuration is invalid. For schema validation
	//	                      failures, status details include a SchemaValidationError
	//	                      message.
	//	FAILED_PRECONDITION - The current version does not match the expected version.
	UpdateOrgConfig(context.Context, *UpdateOrgConfigRequest) (*UpdateOrgConfigResponse, error)
	// Gets the configuration for the trust domain.
	GetTrustDomainConfig(context.Context, *GetTrustDomainConfigRequest) (*GetTrustDomainConfigResponse, error)
	// Updates the configuration for the trust domain.
	//
	// Returns:
	//
	//	INVALID_ARGUMENT    - Configuration is invalid. For schema validation
	//	                      failures, status details include a SchemaValidationError
	//	                      message.
	//	FAILED_PRECONDITION - The current version does not match the expected version.
	UpdateTrustDomainConfig(context.Context, *UpdateTrustDomainConfigRequest) (*UpdateTrustDomainConfigResponse, error)
	// Gets the configuration for the cluster.
	GetClusterConfig(context.Context, *GetClusterConfigRequest) (*GetClusterConfigResponse, error)
	// Updates the configuration for the cluster.
	//
	// Returns:
	//
	//	INVALID_ARGUMENT    - Configuration is invalid. For schema validation
	//	                      failures, status details include a SchemaValidationError
	//	                      message.
	//	FAILED_PRECONDITION - The current version does not match the expected version.
	UpdateClusterConfig(context.Context, *UpdateClusterConfigRequest) (*UpdateClusterConfigResponse, error)
	mustEmbedUnimplementedAPIServer()
}

// UnimplementedAPIServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAPIServer struct{}

func (UnimplementedAPIServer) GetOrgConfig(context.Context, *GetOrgConfigRequest) (*GetOrgConfigResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetOrgConfig not implemented")
}
func (UnimplementedAPIServer) UpdateOrgConfig(context.Context, *UpdateOrgConfigRequest) (*UpdateOrgConfigResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateOrgConfig not implemented")
}
func (UnimplementedAPIServer) GetTrustDomainConfig(context.Context, *GetTrustDomainConfigRequest) (*GetTrustDomainConfigResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetTrustDomainConfig not implemented")
}
func (UnimplementedAPIServer) UpdateTrustDomainConfig(context.Context, *UpdateTrustDomainConfigRequest) (*UpdateTrustDomainConfigResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateTrustDomainConfig not implemented")
}
func (UnimplementedAPIServer) GetClusterConfig(context.Context, *GetClusterConfigRequest) (*GetClusterConfigResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetClusterConfig not implemented")
}
func (UnimplementedAPIServer) UpdateClusterConfig(context.Context, *UpdateClusterConfigRequest) (*UpdateClusterConfigResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateClusterConfig not implemented")
}
func (UnimplementedAPIServer) mustEmbedUnimplementedAPIServer() {}
func (UnimplementedAPIServer) testEmbeddedByValue()             {}

// UnsafeAPIServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to APIServer will
// result in compilation errors.
type UnsafeAPIServer interface {
	mustEmbedUnimplementedAPIServer()
}

func RegisterAPIServer(s grpc.ServiceRegistrar, srv APIServer) {
	// If the following call pancis, it indicates UnimplementedAPIServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&API_ServiceDesc, srv)
}

func _API_GetOrgConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetOrgConfigRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(APIServer).GetOrgConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: API_GetOrgConfig_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(APIServer).GetOrgConfig(ctx, req.(*GetOrgConfigRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _API_UpdateOrgConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateOrgConfigRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(APIServer).UpdateOrgConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: API_UpdateOrgConfig_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(APIServer).UpdateOrgConfig(ctx, req.(*UpdateOrgConfigRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _API_GetTrustDomainConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTrustDomainConfigRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(APIServer).GetTrustDomainConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: API_GetTrustDomainConfig_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(APIServer).GetTrustDomainConfig(ctx, req.(*GetTrustDomainConfigRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _API_UpdateTrustDomainConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateTrustDomainConfigRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(APIServer).UpdateTrustDomainConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: API_UpdateTrustDomainConfig_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(APIServer).UpdateTrustDomainConfig(ctx, req.(*UpdateTrustDomainConfigRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _API_GetClusterConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetClusterConfigRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(APIServer).GetClusterConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: API_GetClusterConfig_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(APIServer).GetClusterConfig(ctx, req.(*GetClusterConfigRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _API_UpdateClusterConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateClusterConfigRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(APIServer).UpdateClusterConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: API_UpdateClusterConfig_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(APIServer).UpdateClusterConfig(ctx, req.(*UpdateClusterConfigRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// API_ServiceDesc is the grpc.ServiceDesc for API service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var API_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "com.spirl.api.v1.config.API",
	HandlerType: (*APIServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetOrgConfig",
			Handler:    _API_GetOrgConfig_Handler,
		},
		{
			MethodName: "UpdateOrgConfig",
			Handler:    _API_UpdateOrgConfig_Handler,
		},
		{
			MethodName: "GetTrustDomainConfig",
			Handler:    _API_GetTrustDomainConfig_Handler,
		},
		{
			MethodName: "UpdateTrustDomainConfig",
			Handler:    _API_UpdateTrustDomainConfig_Handler,
		},
		{
			MethodName: "GetClusterConfig",
			Handler:    _API_GetClusterConfig_Handler,
		},
		{
			MethodName: "UpdateClusterConfig",
			Handler:    _API_UpdateClusterConfig_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/v1/configapi/api.proto",
}
