// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        (unknown)
// source: api/v1/listing/api.proto

package listing

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// FilterOperator names the comparison applied by a FieldFilter. Operator
// support is per-field and per-entity: a server rejects unsupported pairings
// with INVALID_ARGUMENT.
type FilterOperator int32

const (
	FilterOperator_FILTER_OPERATOR_UNSPECIFIED           FilterOperator = 0
	FilterOperator_FILTER_OPERATOR_EQUAL                 FilterOperator = 1
	FilterOperator_FILTER_OPERATOR_CONTAINS              FilterOperator = 3
	FilterOperator_FILTER_OPERATOR_GREATER_THAN_OR_EQUAL FilterOperator = 4
	FilterOperator_FILTER_OPERATOR_LESS_THAN_OR_EQUAL    FilterOperator = 5
)

// Enum value maps for FilterOperator.
var (
	FilterOperator_name = map[int32]string{
		0: "FILTER_OPERATOR_UNSPECIFIED",
		1: "FILTER_OPERATOR_EQUAL",
		3: "FILTER_OPERATOR_CONTAINS",
		4: "FILTER_OPERATOR_GREATER_THAN_OR_EQUAL",
		5: "FILTER_OPERATOR_LESS_THAN_OR_EQUAL",
	}
	FilterOperator_value = map[string]int32{
		"FILTER_OPERATOR_UNSPECIFIED":           0,
		"FILTER_OPERATOR_EQUAL":                 1,
		"FILTER_OPERATOR_CONTAINS":              3,
		"FILTER_OPERATOR_GREATER_THAN_OR_EQUAL": 4,
		"FILTER_OPERATOR_LESS_THAN_OR_EQUAL":    5,
	}
)

func (x FilterOperator) Enum() *FilterOperator {
	p := new(FilterOperator)
	*p = x
	return p
}

func (x FilterOperator) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (FilterOperator) Descriptor() protoreflect.EnumDescriptor {
	return file_api_v1_listing_api_proto_enumTypes[0].Descriptor()
}

func (FilterOperator) Type() protoreflect.EnumType {
	return &file_api_v1_listing_api_proto_enumTypes[0]
}

func (x FilterOperator) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use FilterOperator.Descriptor instead.
func (FilterOperator) EnumDescriptor() ([]byte, []int) {
	return file_api_v1_listing_api_proto_rawDescGZIP(), []int{0}
}

// SortOrder selects ascending or descending order for a FieldSort entry.
type SortOrder int32

const (
	SortOrder_SORT_ORDER_UNSPECIFIED SortOrder = 0
	SortOrder_SORT_ORDER_ASC         SortOrder = 1
	SortOrder_SORT_ORDER_DESC        SortOrder = 2
)

// Enum value maps for SortOrder.
var (
	SortOrder_name = map[int32]string{
		0: "SORT_ORDER_UNSPECIFIED",
		1: "SORT_ORDER_ASC",
		2: "SORT_ORDER_DESC",
	}
	SortOrder_value = map[string]int32{
		"SORT_ORDER_UNSPECIFIED": 0,
		"SORT_ORDER_ASC":         1,
		"SORT_ORDER_DESC":        2,
	}
)

func (x SortOrder) Enum() *SortOrder {
	p := new(SortOrder)
	*p = x
	return p
}

func (x SortOrder) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SortOrder) Descriptor() protoreflect.EnumDescriptor {
	return file_api_v1_listing_api_proto_enumTypes[1].Descriptor()
}

func (SortOrder) Type() protoreflect.EnumType {
	return &file_api_v1_listing_api_proto_enumTypes[1]
}

func (x SortOrder) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SortOrder.Descriptor instead.
func (SortOrder) EnumDescriptor() ([]byte, []int) {
	return file_api_v1_listing_api_proto_rawDescGZIP(), []int{1}
}

// FieldFilter is a single entry in a list-request filter set. The `field`
// is the int32 value of the entity-specific FilterField enum defined in the
// caller's API package.
type FieldFilter struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Required. The int32 value of the entity-specific FilterField enum.
	// Must be non-zero (the enum's UNSPECIFIED value is rejected).
	Field int32 `protobuf:"varint,1,opt,name=field,proto3" json:"field,omitempty"`
	// Required. Filter operator.
	Operator FilterOperator `protobuf:"varint,2,opt,name=operator,proto3,enum=com.spirl.api.v1.listing.FilterOperator" json:"operator,omitempty"`
	// Required. Value to filter by. The value is a string regardless of the
	// underlying column type; the server parses it per-field. The accepted
	// encoding depends on the field type:
	//   - string columns: the literal value.
	//   - integer columns: the decimal representation (e.g. "42").
	//   - boolean columns: "true" or "false".
	//   - enum columns: the proto enum value name (e.g.
	//     "KUBERNETES_WORKLOAD_TYPE_DEPLOYMENT") or its decimal int32 value,
	//     per the field's documentation.
	//   - timestamp columns: an RFC 3339 timestamp (e.g.
	//     "2025-01-02T15:04:05Z").
	//
	// Individual fields may layer additional decoding on top of these
	// (for example, mapping an enum-named value to an ordinal-range filter);
	// see the per-field documentation for the exact accepted encoding.
	// Unparseable values yield INVALID_ARGUMENT with a field detail.
	Value string `protobuf:"bytes,3,opt,name=value,proto3" json:"value,omitempty"`
}

func (x *FieldFilter) Reset() {
	*x = FieldFilter{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_v1_listing_api_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FieldFilter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FieldFilter) ProtoMessage() {}

func (x *FieldFilter) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_listing_api_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FieldFilter.ProtoReflect.Descriptor instead.
func (*FieldFilter) Descriptor() ([]byte, []int) {
	return file_api_v1_listing_api_proto_rawDescGZIP(), []int{0}
}

func (x *FieldFilter) GetField() int32 {
	if x != nil {
		return x.Field
	}
	return 0
}

func (x *FieldFilter) GetOperator() FilterOperator {
	if x != nil {
		return x.Operator
	}
	return FilterOperator_FILTER_OPERATOR_UNSPECIFIED
}

func (x *FieldFilter) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

// FieldSort is a single entry in a list-request sort set. The `field` is
// the int32 value of the entity-specific SortField enum defined in the
// caller's API package.
type FieldSort struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Required. The int32 value of the entity-specific SortField enum.
	// Must be non-zero (the enum's UNSPECIFIED value is rejected).
	Field int32 `protobuf:"varint,1,opt,name=field,proto3" json:"field,omitempty"`
	// Required. Sort order (ascending or descending).
	Order SortOrder `protobuf:"varint,2,opt,name=order,proto3,enum=com.spirl.api.v1.listing.SortOrder" json:"order,omitempty"`
}

func (x *FieldSort) Reset() {
	*x = FieldSort{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_v1_listing_api_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FieldSort) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FieldSort) ProtoMessage() {}

func (x *FieldSort) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_listing_api_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FieldSort.ProtoReflect.Descriptor instead.
func (*FieldSort) Descriptor() ([]byte, []int) {
	return file_api_v1_listing_api_proto_rawDescGZIP(), []int{1}
}

func (x *FieldSort) GetField() int32 {
	if x != nil {
		return x.Field
	}
	return 0
}

func (x *FieldSort) GetOrder() SortOrder {
	if x != nil {
		return x.Order
	}
	return SortOrder_SORT_ORDER_UNSPECIFIED
}

var File_api_v1_listing_api_proto protoreflect.FileDescriptor

var file_api_v1_listing_api_proto_rawDesc = []byte{
	0x0a, 0x18, 0x61, 0x70, 0x69, 0x2f, 0x76, 0x31, 0x2f, 0x6c, 0x69, 0x73, 0x74, 0x69, 0x6e, 0x67,
	0x2f, 0x61, 0x70, 0x69, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x18, 0x63, 0x6f, 0x6d, 0x2e,
	0x73, 0x70, 0x69, 0x72, 0x6c, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x76, 0x31, 0x2e, 0x6c, 0x69, 0x73,
	0x74, 0x69, 0x6e, 0x67, 0x1a, 0x1b, 0x62, 0x75, 0x66, 0x2f, 0x76, 0x61, 0x6c, 0x69, 0x64, 0x61,
	0x74, 0x65, 0x2f, 0x76, 0x61, 0x6c, 0x69, 0x64, 0x61, 0x74, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x22, 0x92, 0x01, 0x0a, 0x0b, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x46, 0x69, 0x6c, 0x74, 0x65,
	0x72, 0x12, 0x1d, 0x0a, 0x05, 0x66, 0x69, 0x65, 0x6c, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05,
	0x42, 0x07, 0xba, 0x48, 0x04, 0x1a, 0x02, 0x20, 0x00, 0x52, 0x05, 0x66, 0x69, 0x65, 0x6c, 0x64,
	0x12, 0x4e, 0x0a, 0x08, 0x6f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x6f, 0x72, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x0e, 0x32, 0x28, 0x2e, 0x63, 0x6f, 0x6d, 0x2e, 0x73, 0x70, 0x69, 0x72, 0x6c, 0x2e, 0x61,
	0x70, 0x69, 0x2e, 0x76, 0x31, 0x2e, 0x6c, 0x69, 0x73, 0x74, 0x69, 0x6e, 0x67, 0x2e, 0x46, 0x69,
	0x6c, 0x74, 0x65, 0x72, 0x4f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x6f, 0x72, 0x42, 0x08, 0xba, 0x48,
	0x05, 0x82, 0x01, 0x02, 0x20, 0x00, 0x52, 0x08, 0x6f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x6f, 0x72,
	0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x22, 0x6f, 0x0a, 0x09, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x53,
	0x6f, 0x72, 0x74, 0x12, 0x1d, 0x0a, 0x05, 0x66, 0x69, 0x65, 0x6c, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x05, 0x42, 0x07, 0xba, 0x48, 0x04, 0x1a, 0x02, 0x20, 0x00, 0x52, 0x05, 0x66, 0x69, 0x65,
	0x6c, 0x64, 0x12, 0x43, 0x0a, 0x05, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x0e, 0x32, 0x23, 0x2e, 0x63, 0x6f, 0x6d, 0x2e, 0x73, 0x70, 0x69, 0x72, 0x6c, 0x2e, 0x61, 0x70,
	0x69, 0x2e, 0x76, 0x31, 0x2e, 0x6c, 0x69, 0x73, 0x74, 0x69, 0x6e, 0x67, 0x2e, 0x53, 0x6f, 0x72,
	0x74, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x42, 0x08, 0xba, 0x48, 0x05, 0x82, 0x01, 0x02, 0x20, 0x00,
	0x52, 0x05, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x2a, 0xde, 0x01, 0x0a, 0x0e, 0x46, 0x69, 0x6c, 0x74,
	0x65, 0x72, 0x4f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x6f, 0x72, 0x12, 0x1f, 0x0a, 0x1b, 0x46, 0x49,
	0x4c, 0x54, 0x45, 0x52, 0x5f, 0x4f, 0x50, 0x45, 0x52, 0x41, 0x54, 0x4f, 0x52, 0x5f, 0x55, 0x4e,
	0x53, 0x50, 0x45, 0x43, 0x49, 0x46, 0x49, 0x45, 0x44, 0x10, 0x00, 0x12, 0x19, 0x0a, 0x15, 0x46,
	0x49, 0x4c, 0x54, 0x45, 0x52, 0x5f, 0x4f, 0x50, 0x45, 0x52, 0x41, 0x54, 0x4f, 0x52, 0x5f, 0x45,
	0x51, 0x55, 0x41, 0x4c, 0x10, 0x01, 0x12, 0x1c, 0x0a, 0x18, 0x46, 0x49, 0x4c, 0x54, 0x45, 0x52,
	0x5f, 0x4f, 0x50, 0x45, 0x52, 0x41, 0x54, 0x4f, 0x52, 0x5f, 0x43, 0x4f, 0x4e, 0x54, 0x41, 0x49,
	0x4e, 0x53, 0x10, 0x03, 0x12, 0x29, 0x0a, 0x25, 0x46, 0x49, 0x4c, 0x54, 0x45, 0x52, 0x5f, 0x4f,
	0x50, 0x45, 0x52, 0x41, 0x54, 0x4f, 0x52, 0x5f, 0x47, 0x52, 0x45, 0x41, 0x54, 0x45, 0x52, 0x5f,
	0x54, 0x48, 0x41, 0x4e, 0x5f, 0x4f, 0x52, 0x5f, 0x45, 0x51, 0x55, 0x41, 0x4c, 0x10, 0x04, 0x12,
	0x26, 0x0a, 0x22, 0x46, 0x49, 0x4c, 0x54, 0x45, 0x52, 0x5f, 0x4f, 0x50, 0x45, 0x52, 0x41, 0x54,
	0x4f, 0x52, 0x5f, 0x4c, 0x45, 0x53, 0x53, 0x5f, 0x54, 0x48, 0x41, 0x4e, 0x5f, 0x4f, 0x52, 0x5f,
	0x45, 0x51, 0x55, 0x41, 0x4c, 0x10, 0x05, 0x22, 0x04, 0x08, 0x02, 0x10, 0x02, 0x2a, 0x19, 0x46,
	0x49, 0x4c, 0x54, 0x45, 0x52, 0x5f, 0x4f, 0x50, 0x45, 0x52, 0x41, 0x54, 0x4f, 0x52, 0x5f, 0x4e,
	0x4f, 0x54, 0x5f, 0x45, 0x51, 0x55, 0x41, 0x4c, 0x2a, 0x50, 0x0a, 0x09, 0x53, 0x6f, 0x72, 0x74,
	0x4f, 0x72, 0x64, 0x65, 0x72, 0x12, 0x1a, 0x0a, 0x16, 0x53, 0x4f, 0x52, 0x54, 0x5f, 0x4f, 0x52,
	0x44, 0x45, 0x52, 0x5f, 0x55, 0x4e, 0x53, 0x50, 0x45, 0x43, 0x49, 0x46, 0x49, 0x45, 0x44, 0x10,
	0x00, 0x12, 0x12, 0x0a, 0x0e, 0x53, 0x4f, 0x52, 0x54, 0x5f, 0x4f, 0x52, 0x44, 0x45, 0x52, 0x5f,
	0x41, 0x53, 0x43, 0x10, 0x01, 0x12, 0x13, 0x0a, 0x0f, 0x53, 0x4f, 0x52, 0x54, 0x5f, 0x4f, 0x52,
	0x44, 0x45, 0x52, 0x5f, 0x44, 0x45, 0x53, 0x43, 0x10, 0x02, 0x42, 0x2e, 0x5a, 0x2c, 0x67, 0x69,
	0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x73, 0x70, 0x69, 0x72, 0x6c, 0x2f, 0x73,
	0x70, 0x69, 0x72, 0x6c, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2f, 0x61, 0x70, 0x69, 0x2f,
	0x76, 0x31, 0x2f, 0x6c, 0x69, 0x73, 0x74, 0x69, 0x6e, 0x67, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
}

var (
	file_api_v1_listing_api_proto_rawDescOnce sync.Once
	file_api_v1_listing_api_proto_rawDescData = file_api_v1_listing_api_proto_rawDesc
)

func file_api_v1_listing_api_proto_rawDescGZIP() []byte {
	file_api_v1_listing_api_proto_rawDescOnce.Do(func() {
		file_api_v1_listing_api_proto_rawDescData = protoimpl.X.CompressGZIP(file_api_v1_listing_api_proto_rawDescData)
	})
	return file_api_v1_listing_api_proto_rawDescData
}

var file_api_v1_listing_api_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_api_v1_listing_api_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_api_v1_listing_api_proto_goTypes = []any{
	(FilterOperator)(0), // 0: com.spirl.api.v1.listing.FilterOperator
	(SortOrder)(0),      // 1: com.spirl.api.v1.listing.SortOrder
	(*FieldFilter)(nil), // 2: com.spirl.api.v1.listing.FieldFilter
	(*FieldSort)(nil),   // 3: com.spirl.api.v1.listing.FieldSort
}
var file_api_v1_listing_api_proto_depIdxs = []int32{
	0, // 0: com.spirl.api.v1.listing.FieldFilter.operator:type_name -> com.spirl.api.v1.listing.FilterOperator
	1, // 1: com.spirl.api.v1.listing.FieldSort.order:type_name -> com.spirl.api.v1.listing.SortOrder
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_api_v1_listing_api_proto_init() }
func file_api_v1_listing_api_proto_init() {
	if File_api_v1_listing_api_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_api_v1_listing_api_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*FieldFilter); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_v1_listing_api_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*FieldSort); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_api_v1_listing_api_proto_rawDesc,
			NumEnums:      2,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_api_v1_listing_api_proto_goTypes,
		DependencyIndexes: file_api_v1_listing_api_proto_depIdxs,
		EnumInfos:         file_api_v1_listing_api_proto_enumTypes,
		MessageInfos:      file_api_v1_listing_api_proto_msgTypes,
	}.Build()
	File_api_v1_listing_api_proto = out.File
	file_api_v1_listing_api_proto_rawDesc = nil
	file_api_v1_listing_api_proto_goTypes = nil
	file_api_v1_listing_api_proto_depIdxs = nil
}
